// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAmmoTypeLaser.h"

UFGAmmoTypeLaser::UFGAmmoTypeLaser(){ }
float UFGAmmoTypeLaser::GetTotalHitDamageAmount_Implementation(const FHitResult& hitResult, const UFGDamageType* damageType){ return float(); }
