// This file has been automatically generated by the Unreal Header Implementation tool

#include "Equipment/FGAmmoTypeProjectile.h"

UFGAmmoTypeProjectile::UFGAmmoTypeProjectile(){ }
void UFGAmmoTypeProjectile::FireAmmunition_Implementation(){ }
void UFGAmmoTypeProjectile::SetupProjectile_Implementation(AFGProjectile* projectile){ }
void UFGAmmoTypeProjectile::ProjectileFire(){ }
