// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAmmoTypeHomingBase.h"

UFGAmmoTypeHomingBase::UFGAmmoTypeHomingBase(){ }
bool UFGAmmoTypeHomingBase::GetNewHomingTarget(FHitResult& out_hitResult) const{ return bool(); }
bool UFGAmmoTypeHomingBase::CanHomingHitTarget_Implementation(const AActor* target) const{ return bool(); }
EHomingPriority UFGAmmoTypeHomingBase::GetPriorityLevelForActor_Implementation(const AActor* actor) const{ return EHomingPriority(); }
