// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGEquipmentStunSpear.h"

AFGEquipmentStunSpear::AFGEquipmentStunSpear(){ }
void AFGEquipmentStunSpear::DoAttack(){ }
void AFGEquipmentStunSpear::HandleDefaultEquipmentActionEvent(EDefaultEquipmentAction action, EDefaultEquipmentActionEvent actionEvent){ }
void AFGEquipmentStunSpear::Server_ShockEnemy_Implementation(const FVector& attackDirection){ }
void AFGEquipmentStunSpear::Server_PlayStunEffects_Implementation(bool secondSwing){ }
void AFGEquipmentStunSpear::Multicast_PlayHitEffects_Implementation(const TArray<FHitResult> &hitResults){ }
void AFGEquipmentStunSpear::Multicast_PlayStunEffects_Implementation(bool secondSwing){ }
