// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGEquipmentZipline.h"

AFGEquipmentZipline::AFGEquipmentZipline(){ }
void AFGEquipmentZipline::AddEquipmentActionBindings(){ }
void AFGEquipmentZipline::UnEquip(){ }
void AFGEquipmentZipline::Tick(float delta){ }
void AFGEquipmentZipline::ZiplineEnd(){ }
void AFGEquipmentZipline::Server_DoDrop_Implementation(){ }
bool AFGEquipmentZipline::Server_DoDrop_Validate(){ return bool(); }
void AFGEquipmentZipline::DoDrop(){ }
void AFGEquipmentZipline::Server_JumpExit_Implementation(){ }
bool AFGEquipmentZipline::Server_JumpExit_Validate(){ return bool(); }
void AFGEquipmentZipline::JumpExit(){ }
void AFGEquipmentZipline::Input_Crouch(const FInputActionValue& actionValue){ }
void AFGEquipmentZipline::Input_Jump(const FInputActionValue& actionValue){ }
void AFGEquipmentZipline::TryToGrab(){ }
bool AFGEquipmentZipline::CanGrab(AActor* attachActor, const FVector& point1, const FVector& point2) const{ return bool(); }
void AFGEquipmentZipline::HandleDefaultEquipmentActionEvent(EDefaultEquipmentAction action, EDefaultEquipmentActionEvent actionEvent){ }
void AFGEquipmentZipline::SetWantsToGrab(bool wantToGrab){ }
void AFGEquipmentZipline::MakeActiveNoise(){ }
