// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGEquipmentStunSpear.h"

AFGEquipmentStunSpear::AFGEquipmentStunSpear(){ }
void AFGEquipmentStunSpear::AddEquipmentActionBindings(){ }
void AFGEquipmentStunSpear::DoAttack(){ }
void AFGEquipmentStunSpear::OnHitTarget_Implementation(){ }
void AFGEquipmentStunSpear::Server_ShockEnemy_Implementation(FVector attackDirection){ }
bool AFGEquipmentStunSpear::Server_ShockEnemy_Validate(FVector attackDirection){ return bool(); }
void AFGEquipmentStunSpear::Multicast_PlayHitEffects_Implementation(const TArray<FHitResult> &hitResults){ }
void AFGEquipmentStunSpear::OnFirePressed(){ }
