// This file has been automatically generated by the Unreal Header Implementation tool

#include "Equipment/FGEquipmentStunSpear.h"

AFGEquipmentStunSpear::AFGEquipmentStunSpear(){ }
void AFGEquipmentStunSpear::Local_SwingWeapon(){ }
void AFGEquipmentStunSpear::Local_Attack(){ }
void AFGEquipmentStunSpear::HandleDefaultEquipmentActionEvent(EDefaultEquipmentAction action, EDefaultEquipmentActionEvent actionEvent){ }
void AFGEquipmentStunSpear::PlayHitEffectsInternal(const TArray<FHitResult>& hitLocations){ }
void AFGEquipmentStunSpear::Server_ProcessAttack_Implementation(const TArray<FHitResult>& hitResults){ }
void AFGEquipmentStunSpear::Server_ProcessPlayerSwing_Implementation(bool secondSwing){ }
void AFGEquipmentStunSpear::Multicast_PlayHitEffects_Implementation(const TArray<FHitResult> &hitResults){ }
void AFGEquipmentStunSpear::Multicast_PlaySwingEffects_Implementation(bool secondSwing){ }
