// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGEquipmentBoomBox.h"

AFGEquipmentBoomBox::AFGEquipmentBoomBox(){ }
void AFGEquipmentBoomBox::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
TArray< TSubclassOf< class UFGTapeDescriptor > > AFGEquipmentBoomBox::GetAvailableTapes(){ return TArray<TSubclassOf<class UFGTapeDescriptor> >(); }
