// This file has been automatically generated by the Unreal Header Implementation tool

#include "Equipment/FGEquipmentDecoration.h"

AFGEquipmentDecoration::AFGEquipmentDecoration(){ }
void AFGEquipmentDecoration::Tick(float DeltaSeconds){ }
void AFGEquipmentDecoration::OnPrimaryFirePressed(){ }
void AFGEquipmentDecoration::Server_PrimaryFire_Implementation(){ }
bool AFGEquipmentDecoration::Server_PrimaryFire_Validate(){ return bool(); }
void AFGEquipmentDecoration::HandleDefaultEquipmentActionEvent(EDefaultEquipmentAction action, EDefaultEquipmentActionEvent actionEvent){ }
