// This file has been automatically generated by the Unreal Header Implementation tool

#include "Equipment/FGGasMask.h"

AFGGasMask::AFGGasMask(){ }
void AFGGasMask::Tick(const float deltaTime){ }
float AFGGasMask::AdjustDamage_Implementation(const float damageAmount, const  UDamageType* damageType,  AController* instigatedBy, AActor* damageCauser){ return float(); }
void AFGGasMask::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGGasMask::PostProcessEnabled_OnRep(){ }
bool AFGGasMask::IsInGasCloud() const{ return bool(); }
