// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGObjectScanner.h"

AFGObjectScanner::AFGObjectScanner(){ }
void AFGObjectScanner::BeginPlay(){ }
void AFGObjectScanner::Tick(float deltaTime){ }
void AFGObjectScanner::Equip( AFGCharacterPlayer* character){ }
void AFGObjectScanner::UnEquip(){ }
bool AFGObjectScanner::CycleForward(){ return bool(); }
bool AFGObjectScanner::CycleBackward(){ return bool(); }
void AFGObjectScanner::GetAvailableScannableDescriptors(TArray < TSubclassOf<UFGItemDescriptor> >& out_availableDescriptors){ }
void AFGObjectScanner::SetScannableDescriptor(TSubclassOf<UFGItemDescriptor> newScannableDescriptor){ }
bool AFGObjectScanner::Internal_CycleObjects(ECycleDirection direction){ return bool(); }
void AFGObjectScanner::RemoveInvalidObjectsFromCache(TSubclassOf< AActor > scannableClass){ }
void AFGObjectScanner::UpdateClosestObject(){ }
void AFGObjectScanner::Internal_PlayBeep(){ }
void AFGObjectScanner::TryToEquipDefaultObject(){ }
void AFGObjectScannerAttachment::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGObjectScannerAttachment::OnRep_IsBeeping(){ }
void AFGObjectScannerAttachment::OnRep_ScannerLightColor(){ }
