// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGParachute.h"

AFGParachute::AFGParachute(){ }
void AFGParachute::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGParachute::Tick(float DeltaSeconds){ }
void AFGParachute::UnEquip(){ }
void AFGParachute::Input_Deploy(const FInputActionValue& actionValue){ }
void AFGParachute::Input_UnDeploy(const FInputActionValue& actionValue){ }
void AFGParachute::Deploy(){ }
void AFGParachute::StopDeploy(){ }
void AFGParachute::AddEquipmentActionBindings(){ }
float AFGParachute::GetCharacterUseDistanceOverride() const{ return float(); }
void AFGParachute::Server_Deploy_Implementation(){ }
void AFGParachute::Server_StopDeploy_Implementation(){ }
void AFGParachute::Client_NotifyDeployFailed_Implementation(){ }
bool AFGParachute::AttemptDeployLocal(){ return bool(); }
void AFGParachute::StopDeployLocal(){ }
void AFGParachute::Authority_SetDeployed(bool isDeployedNow){ }
void AFGParachute::OnRep_IsDeployed(){ }
