// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWeaponAttachment.h"

void AFGWeaponAttachment::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGWeaponAttachment::Multicast_PlayFireEffect_Implementation(UFGAmmoType* ammoType){ }
void AFGWeaponAttachment::PlayFireEffect_Implementation(UFGAmmoType* ammoType){ }
void AFGWeaponAttachment::Multicast_PlayBeginFireEffect_Implementation(const FVector& location){ }
void AFGWeaponAttachment::Multicast_PlayReloadEffectMulticast_Implementation(){ }
void AFGWeaponAttachment::Multicast_SetIsLoaded_Implementation(bool isLoaded){ }
