// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAudioVolumeSubsystem.h"

#if WITH_AUDIO_DEBUG
void AFGAudioVolumeSubsystem::AudioVolumeDebuggingChanged(IConsoleVariable* var){ }
#endif 
AFGAudioVolumeSubsystem::AFGAudioVolumeSubsystem(){ }
void AFGAudioVolumeSubsystem::Tick(float dt){ }
void AFGAudioVolumeSubsystem::BeginPlay(){ }
void AFGAudioVolumeSubsystem::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
bool AFGAudioVolumeSubsystem::ShouldUpdateWorld(UWorld* world) const{ return bool(); }
void AFGAudioVolumeSubsystem::UpdateWorld(UWorld* world){ }
float AFGAudioVolumeSubsystem::GetCloseDistance( AFGAmbientVolume* ambientVolume) const{ return float(); }
