// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBlueprintProxy.h"

#if !UE_BUILD_SHIPPING
void AFGBlueprintProxy::DisplayDebugInfo() const{ }
#endif 
AFGBlueprintProxy::AFGBlueprintProxy(){ }
void AFGBlueprintProxy::BeginPlay(){ }
void AFGBlueprintProxy::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBlueprintProxy::Tick(float DeltaSeconds){ }
void AFGBlueprintProxy::RegisterBuildable( AFGBuildable* buildable){ }
void AFGBlueprintProxy::UnregisterBuildable( AFGBuildable* buildable){ }
int32 AFGBlueprintProxy::CollectBuildables(TArray<  AFGBuildable* >& out_buildables) const{ return int32(); }
void AFGBlueprintProxy::PreSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGBlueprintProxy::PostSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGBlueprintProxy::PreLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGBlueprintProxy::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGBlueprintProxy::GatherDependencies_Implementation(TArray< UObject* >& out_dependentObjects){ }
bool AFGBlueprintProxy::NeedTransform_Implementation(){ return bool(); }
bool AFGBlueprintProxy::ShouldSave_Implementation() const{ return bool(); }
void AFGBlueprintProxy::OnRep_BlueprintName(){ }
void AFGBlueprintProxy::OnRep_LocalBounds(){ }
void AFGBlueprintProxy::AssignBuildables(const TArray<  AFGBuildable* >& buildables){ }
