// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildingTagInterface.h"

UFGBuildingTagInterface::UFGBuildingTagInterface(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {}
