// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePillar.h"

AFGBuildablePillar::AFGBuildablePillar(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void AFGBuildablePillar::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
AFGBuildablePillarLightweight::AFGBuildablePillarLightweight(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
