// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableBeam.h"

AFGBuildableBeam::AFGBuildableBeam(){ }
void AFGBuildableBeam::BeginPlay(){ }
void AFGBuildableBeam::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBuildableBeam::GetAttachmentPoints(TArray< const FFGAttachmentPoint* >& out_points) const{ }
void AFGBuildableBeam::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
int32 AFGBuildableBeam::GetDismantleRefundReturnsMultiplier() const{ return int32(); }
void AFGBuildableBeam::SetLength(float NewLength){ }
void AFGBuildableBeam::OnRep_Length(){ }
