// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildEffectActor.h"

AFGBuildEffectActor::AFGBuildEffectActor(){ }
void AFGBuildEffectActor::Tick(float DeltaTime){ }
void AFGBuildEffectActor::CreateVisuals(){ }
TArray<UMeshComponent*> AFGBuildEffectActor::CreateStaticMesh(UMeshComponent* SourceComponent, const FTransform& sourceActorTransform){ return TArray<UMeshComponent*>(); }
void AFGBuildEffectActor::SetupThrowQueue(){ }
void AFGBuildEffectActor::SetRecipe(TSubclassOf<UFGRecipe> inRecipe, AFGBuildable* buildable){ }
float AFGBuildEffectActor::GetTotalSplineLength() const{ return float(); }
FTransform AFGBuildEffectActor::GetTransformOnSplines(bool bWorldSpace) const{ return FTransform(); }
FBuildEffectEnded& AFGBuildEffectActor::GetBind(UClass* actorClass){ return *(new FBuildEffectEnded); }
void AFGBuildEffectActor::UpdateCostQueue(){ }
void AFGBuildEffectActor::OnCostActorReachedTarget(){ }
void AFGBuildEffectActor::Start(){ }
void AFGBuildEffectActor::Stop(){ }
void AFGBuildEffectActor::UpdateSplineBuildables(float Dt){ }
void AFGBuildEffectActor::UpdateGenericBuildables(float Dt){ }
void AFGBuildEffectActor::UpdateWires(){ }
void AFGBuildEffectActor::CalculateBuildEffectBounds(){ }
TArray<class USplineComponent*> AFGBuildEffectActor::GetBeltSourceSplinesOrdered(const TArray<class AFGBuildableConveyorBelt*>& inBelts, TArray<AActor*>& orderedActors) const{ return TArray<class USplineComponent*>(); }
TArray<class USplineComponent*> AFGBuildEffectActor::GetPipeSourceSplineOrdered(const TArray<class AFGBuildablePipeBase*>& inPipes, TArray<AActor*>& orderedActors) const{ return TArray<class USplineComponent*>(); }
