// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCineCameraComponent.h"

UFGCineCameraComponent::UFGCineCameraComponent(){ }
void UFGCineCameraComponent::Photo_SetManualFocusDistance(float manualFocusDistance){ }
void UFGCineCameraComponent::Photo_SetAperture(float aperture){ }
void UFGCineCameraComponent::Photo_FocusTrackLookedAtObject(){ }
void UFGCineCameraComponent::Photo_ResetToDefault(){ }
void UFGCineCameraComponent::StartDelayedDestruction(){ }
void UFGCineCameraComponent::StopDelayedDestruction(){ }
void UFGCineCameraComponent::GetDebugStrings(TArray<FString>& out_debugText){ }
void UFGCineCameraComponent::ShowDebug(){ }
void UFGCineCameraComponent::TraceForObjects( FHitResult& out_hitResult){ }
