// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCliffActor.h"

#if WITH_EDITOR
void AFGCliffActor::ConvertStaticMeshActorToOnTopMesh(AActor* SelectedActor, FString& ResultMsg){ }
#endif 
AFGCliffActor::AFGCliffActor(){ }
void AFGCliffActor::BeginPlay(){ }
void AFGCliffActor::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
void AFGCliffActor::OnConstruction(const FTransform& Transform){ }
void AFGCliffActor::GainedSignificance_Implementation(){ }
void AFGCliffActor::LostSignificance_Implementation(){ }
float AFGCliffActor::GetSignificanceRange(){ return float(); }
void AFGCliffActor::CheckOnAsyncTasks(){ }
void FFGCliffGrassWorker::DoWork(){ }
void FFGAsyncCliffGrassBuilderTask::DoWork(){ }
FFGAsyncCliffGrassBuilderTask::~FFGAsyncCliffGrassBuilderTask(){ }
