// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGColoredInstanceMeshProxy.h"

UFGColoredInstanceMeshProxy::UFGColoredInstanceMeshProxy(){ }
void UFGColoredInstanceMeshProxy::BeginPlay(){ }
void UFGColoredInstanceMeshProxy::OnRegister(){ Super::OnRegister(); }
void UFGColoredInstanceMeshProxy::OnUnregister(){ Super::OnUnregister(); }
void UFGColoredInstanceMeshProxy::SetCustomizationData(const FFactoryCustomizationData& customizationData){ }
void UFGColoredInstanceMeshProxy::SetHasPowerData(float newHasPower){ }
void UFGColoredInstanceMeshProxy::SetUserDefinedData(TArray<float> userData){ }
void UFGColoredInstanceMeshProxy::SetInstanced(bool setToInstanced){ }
void UFGColoredInstanceMeshProxy::OnHiddenInGameChanged(){ }
bool UFGColoredInstanceMeshProxy::ShouldCreateRenderState() const{ return bool(); }
void UFGColoredInstanceMeshProxy::InstantiateInternal(){ }
void UFGColoredInstanceMeshProxy::PostLoad(){ Super::PostLoad(); }
