// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGConveyorItemSubSystem.h"

void FInstanceLODs::UpdateVisibility(int32 NumInstances){ }
void FInstanceLODs::AddBucketComponents(int32 Num, AActor* Outer){ }
void FInstanceLODs::AddInstance_Internal(AActor* Outer){ }
AFGConveyorItemSubsystem::AFGConveyorItemSubsystem(){ }
AFGConveyorItemSubsystem* AFGConveyorItemSubsystem::Get(UWorld* world){ return nullptr; }
void AFGConveyorItemSubsystem::RegisterBelt(AFGBuildableConveyorBase* newBelt){ }
void AFGConveyorItemSubsystem::UnRegisterBelt(AFGBuildableConveyorBase* removedBelt){ }
void AFGConveyorItemSubsystem::Tick(float DeltaSeconds){ }
void AFGConveyorItemSubsystem::BeginPlay(){ }
bool AFGConveyorItemSubsystem::HandleDisabledState(){ return bool(); }
void AFGConveyorItemSubsystem::ResolvedRegistered(){ }
void AFGConveyorItemSubsystem::ResolveRemoved(){ }
void AFGConveyorItemSubsystem::ResolveNewTypes(){ }
void AFGConveyorItemSubsystem::ComputeViewCullAndDistance(const FVector PlayerLocation, FConveyorActorContainer< AFGBuildableConveyorBelt* >* Conveyors, FConveyorActorContainer< AFGBuildableConveyorLift* >* Lifts){ }
void AFGConveyorItemSubsystem::GatherTransformData(const TArray<bool> DistancesToUpdate, FConveyorActorContainer< AFGBuildableConveyorBelt* >* Belt, FConveyorActorContainer< AFGBuildableConveyorLift* >* Lifts){ }
void AFGConveyorItemSubsystem::UpdateGPUData(const TArray<bool> DistancesToUpdate){ }
void AFGConveyorItemSubsystem::UpdateBuckets(){ }
void AFGConveyorItemSubsystem::Cleanup(TArray< bool > LodsToUpdate){ }
TArray< bool > AFGConveyorItemSubsystem::UpdateTimers(float DeltaTime){ return TArray<bool>(); }
bool AFGConveyorItemSubsystem::mIsConveyorRendererActive = bool();
