// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGConveyorInstanceMeshBucket.h"

UFGConveyorInstanceMeshBucket::UFGConveyorInstanceMeshBucket(){ }
void UFGConveyorInstanceMeshBucket::Init(){ }
void UFGConveyorInstanceMeshBucket::DirectUpdateInstance(){ }
FBoxSphereBounds UFGConveyorInstanceMeshBucket::CalcBounds(const FTransform& LocalToWorld) const{ return FBoxSphereBounds(); }
