// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureSubsystem.h"

#if WITH_EDITOR
void AFGCreatureSubsystem::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent){ Super::PostEditChangeProperty(PropertyChangedEvent); }
#endif 
AFGCreatureSubsystem::AFGCreatureSubsystem(){ }
void AFGCreatureSubsystem::BeginPlay(){ }
void AFGCreatureSubsystem::Tick(float dt){ }
void AFGCreatureSubsystem::RegisterSpawner( AFGCreatureSpawner* spawner){ }
void AFGCreatureSubsystem::UnregisterSpawner( AFGCreatureSpawner* spawner){ }
void AFGCreatureSubsystem::RegisterCreature( AFGCreature* creature){ }
void AFGCreatureSubsystem::UnregisterCreature( AFGCreature* creature){ }
void AFGCreatureSubsystem::RegisterFlyingBabyCrab( AFGFlyingBabyCrab* babyCrab){ }
void AFGCreatureSubsystem::UnregisterFlyingBabyCrab( AFGFlyingBabyCrab* babyCrab){ }
void AFGCreatureSubsystem::ForceTriggerSpawnersInRange(){ }
void AFGCreatureSubsystem::SetCreatureHostility(ECreatureHostility hostility){ }
bool AFGCreatureSubsystem::IsProtectedCreature(TSubclassOf<  AFGCreature > creatureClass) const{ return bool(); }
void AFGCreatureSubsystem::SetCreatureStressEnabled(bool enabled){ }
AFGCreatureSubsystem* AFGCreatureSubsystem::Get(UWorld* world){ return nullptr; }
AFGCreatureSubsystem* AFGCreatureSubsystem::Get(UObject* worldContext){ return nullptr; }
TSubclassOf< class UFGNoise > AFGCreatureSubsystem::GetNoiseClassFromFName(const FName& name) const{ return TSubclassOf<class UFGNoise>(); }
TSubclassOf< class UFGNoise > AFGCreatureSubsystem::GetNoiseClassFromStimulus(const  FAIStimulus& stimulus) const{ return TSubclassOf<class UFGNoise>(); }
void AFGCreatureSubsystem::OnCreaturePersistenceUpdated( AFGCreature* creature, bool isPersistent){ }
void AFGCreatureSubsystem::UpdateSpawners(){ }
void AFGCreatureSubsystem::ManageCreatures(){ }
void AFGCreatureSubsystem::PopulateNoiseClassArray(){ }
