// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureAnimInstance.h"

UFGCreatureAnimInstance::UFGCreatureAnimInstance(){ }
void UFGCreatureAnimInstance::NativeUpdateAnimation(float DeltaSeconds){ }
