// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGDamageOverTime.h"

UFGDamageOverTime::UFGDamageOverTime(){ }
float UFGDamageOverTime::GetDamageInterval(TSubclassOf< UFGDamageOverTime > dotClass){ return float(); }
TArray< UFGDamageType* > UFGDamageOverTime::GetDamageTypes(TSubclassOf< UFGDamageOverTime > dotClass){ return TArray<UFGDamageType*>(); }
bool UFGDamageOverTime::ShouldBeAppliedToActor(TSubclassOf< UFGDamageOverTime > dotClass,  AActor* actor){ return bool(); }
bool UFGDamageOverTime::ShouldBeAppliedToActor( AActor* actor) const{ return bool(); }
