// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGDestructiveProjectile.h"

AFGDestructiveProjectile::AFGDestructiveProjectile(){ }
void AFGDestructiveProjectile::PopulateDestructionContainers(){ }
void AFGDestructiveProjectile::OnExplode_Implementation(){ }
void AFGDestructiveProjectile::HandleFoliageDestruction(){ }
void AFGDestructiveProjectile::HandleActorDestruction(){ }
