// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGDestructibleActor.h"

AFGDestructibleActor::AFGDestructibleActor(){ }
void AFGDestructibleActor::BeginPlay(){ }
float AFGDestructibleActor::TakeDamage(float damage,  FDamageEvent const& damageEvent, AController* eventInstigator, AActor* damageCauser){ return float(); }
void AFGDestructibleActor::PreSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGDestructibleActor::PostSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGDestructibleActor::PreLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGDestructibleActor::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGDestructibleActor::GatherDependencies_Implementation(TArray< UObject* >& out_dependentObjects){ }
bool AFGDestructibleActor::NeedTransform_Implementation(){ return bool(); }
bool AFGDestructibleActor::ShouldSave_Implementation() const{ return bool(); }
void AFGDestructibleActor::SetDestructibleActorState(EDestructibleActorState newState){ }
void AFGDestructibleActor::ApplyDestructibleActorState(){ }
void AFGDestructibleActor::OnDestructibleFractured(){ }
void AFGDestructibleActor::OnFracturingFinished(){ }
void AFGDestructibleActor::OnRep_DestructibleActorState(){ }
void AFGDestructibleActor::GetLifetimeReplicatedProps(TArray<FLifetimeProperty> & OutLifetimeProps) const { Super::GetLifetimeReplicatedProps(OutLifetimeProps); }
