// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFenceHologram.h"

AFGFenceHologram::AFGFenceHologram(){ }
bool AFGFenceHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
int32 AFGFenceHologram::GetRotationStep() const{ return int32(); }
