// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFoliageStateRepProxy.h"

void FFoliageRemovalHashArray::PostReplicatedAdd(const TArrayView<int32>& AddedIndices, int32 FinalSize){ }
void UFGFoliageRemovalBundle::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void UFGFoliageRemovalBundle::PostInitProperties(){ Super::PostInitProperties(); }
bool UFGFoliageRemovalBundle::IsSupportedForNetworking() const{ return bool(); }
void AFGFoliageStateRepProxy::ConfirmFullyReplicated(UFGFoliageRemovalBundle::FRreplicatorWrapper replicator){ }
AFGFoliageStateRepProxy::AFGFoliageStateRepProxy(){ }
void AFGFoliageStateRepProxy::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGFoliageStateRepProxy::Tick(float DeltaTime){ }
void AFGFoliageStateRepProxy::BeginPlay(){ }
void AFGFoliageStateRepProxy::Server_ConfirmFullyReplicated_Implementation(UFGFoliageRemovalBundle* replicator){ }
void AFGFoliageStateRepProxy::OnFoliageBucketRemoved(const FIntVector& inCell, const UFoliageType* forFoliageType, int32 bucketId){ }
