// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFoliageRemoval.h"

AFGFoliageRemoval::AFGFoliageRemoval(){ }
void AFGFoliageRemoval::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
bool AFGFoliageRemoval::ShouldSave_Implementation() const{ return bool(); }
