// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFoliageTypes.h"

bool FHashableVectorWrapper::operator<(const FVector &V) const{ return bool(); }
bool FFoliageRemovalDataKey::operator==(const FFoliageRemovalDataKey&) const{ return bool(); }
