// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGGenericBuildableHologram.h"

AFGGenericBuildableHologram::AFGGenericBuildableHologram(){ }
void AFGGenericBuildableHologram::BeginPlay(){ }
bool AFGGenericBuildableHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
int32 AFGGenericBuildableHologram::GetRotationStep() const{ return int32(); }
bool AFGGenericBuildableHologram::IsHologramIdenticalToBuildable(AFGBuildable* buildable, const FVector& hologramLocationOffset) const{ return bool(); }
