// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGOutlineComponent.h"

UFGOutlineComponent::UFGOutlineComponent(){ }
UFGOutlineComponent* UFGOutlineComponent::Get(UWorld* world){ return nullptr; }
void UFGOutlineComponent::ShowOutline(AActor* actorToOutline, EOutlineColor color){ }
void UFGOutlineComponent::ShowProxyOutline( UStaticMesh* outlineMesh, const FTransform transform, EOutlineColor color){ }
void UFGOutlineComponent::ShowMultiActorOutline(TArray< AActor* > actorsToOutline, EOutlineColor color){ }
void UFGOutlineComponent::UpdateProxyOutlineMesh( UStaticMesh* newOutlineMesh){ }
void UFGOutlineComponent::UpdateProxyOutlineLocationAndRotation(FVector newLocation, FRotator newRotation){ }
void UFGOutlineComponent::HideOutline(){ }
void UFGOutlineComponent::ShowActorOutline( AActor* actorToOutline, EOutlineColor color){ }
void UFGOutlineComponent::HideActorOutline( AActor* actorToDisableOutlineOn){ }
void UFGOutlineComponent::ShowDismantlePendingMaterial(TArray< AActor* > actorPendingDismantle){ }
void UFGOutlineComponent::ShowDismantlePendingMaterial(AActor* actorPendingDismantle){ }
void UFGOutlineComponent::ShowDismantlePendingMaterialOnActor(AActor* actorPendingForDismantle){ }
bool UFGOutlineComponent::IsOwnedByLocalPlayer(){ return bool(); }
