// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGProximitySubsystem.h"

AFGProximitySubsystem::AFGProximitySubsystem(){ }
void AFGProximitySubsystem::OnEnteredMapArea_Implementation( TSubclassOf<  UFGMapArea > newArea){ }
void AFGProximitySubsystem::OnPawnChanged_Implementation(  APawn* newPawn){ }
UParticleSystem* AFGProximitySubsystem::GetParticleSystemFromMapArea( TSubclassOf<  UFGMapArea > inArea){ return nullptr; }
void AFGProximitySubsystem::SpawnPooledDecal( const UObject* WorldContextObject,  UMaterialInterface* DecalMaterial, FVector DecalSize, FVector Location, FRotator Rotation , 0, 0 ), float LifeSpan ){ }
void AFGProximitySubsystem::BeginPlay(){ }
void AFGProximitySubsystem::Tick( float DeltaTime){ }
