// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGProductionIndicatorInstanceComponent.h"

UFGProductionIndicatorInstanceComponent::UFGProductionIndicatorInstanceComponent(){ }
void UFGProductionIndicatorInstanceComponent::OnProductionStatusChanged(EProductionStatus newStatus){ }
void UFGProductionIndicatorInstanceComponent::ResetIndicatorStatus(){ }
void UFGProductionIndicatorInstanceComponent::SetVisuals(EProductionStatus newStatus){ }
