// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGProximitySubsystem.h"

#if WITH_EDITOR
#endif 
AFGProximitySubsystem::AFGProximitySubsystem(){ }
void AFGProximitySubsystem::SetupPlayerBinds( AFGPlayerController* Player){ }
AFGProximitySubsystem* AFGProximitySubsystem::GetProximitySubsystem(UObject* World){ return nullptr; }
bool AFGProximitySubsystem::IsNearBase(const FVector& Location, float Range, int32 MinimumRequiredBuildables, bool bIgnoreWeight) const{ return bool(); }
void AFGProximitySubsystem::StaticRegisterFactoryBuildingToProximitySystem(AActor* Actor, float Weight){ }
void AFGProximitySubsystem::RegisterFactoryBuildingToProximitySystem(FVector Location, float Weight){ }
void AFGProximitySubsystem::StaticRemoveFactoryBuildingToProximitySystem(AActor* Actor, float Weight){ }
void AFGProximitySubsystem::RemoveFactoryBuildingToProximitySystem(FVector Location, float Weight){ }
void AFGProximitySubsystem::OnEnteredMapArea_Implementation( AFGPlayerControllerBase* playerController, TSubclassOf<  UFGMapArea > newArea){ }
void AFGProximitySubsystem::OnPawnChanged_Implementation( APawn* newPawn){ }
UParticleSystem* AFGProximitySubsystem::GetParticleSystemFromMapArea(TSubclassOf<  UFGMapArea > inArea){ return nullptr; }
void AFGProximitySubsystem::SpawnPooledDecal(const UObject* WorldContextObject,  UMaterialInterface* DecalMaterial, FVector DecalSize, FVector Location, FRotator Rotation , float LifeSpan){ }
void AFGProximitySubsystem::BeginPlay(){ }
void AFGProximitySubsystem::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
void AFGProximitySubsystem::Tick(float DeltaTime){ }
