// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGRainOcclusionActor.h"

FSimpleBuildingInfo FSimpleBuildingInfo::DefaultSquareFoundation(AFGBuildable* Source){ return FSimpleBuildingInfo(); }
FSimpleBuildingInfo::FSimpleBuildingInfo(AFGBuildable* Source){ }
AFGRainOcclusionActor::AFGRainOcclusionActor(){ }
void AFGRainOcclusionActor::Tick(float DeltaSeconds){ }
void AFGRainOcclusionActor::BeginPlay(){ }
void AFGRainOcclusionActor::ForceUpdateOcclusionShapes(const FVector& Location, const float& Range){ }
void AFGRainOcclusionActor::OnTraceCompleted(const FTraceHandle& Handle, FOverlapDatum& Data){ }
void AFGRainOcclusionActor::AddShape(AFGBuildable* Buildable){ }
void AFGRainOcclusionActor::RemoveShape(AFGBuildable* Buildable){ }
void AFGRainOcclusionActor::SetupStaticMeshComponentFlags(UStaticMeshComponent* Component){ }
void AFGRainOcclusionActor::ResolveTracedEntries(){ }
void AFGRainOcclusionActor::SetUpdateRainOccluders(bool bActive){ }
UInstancedStaticMeshComponent* AFGRainOcclusionActor::SetupDefaultOccluderMeshComponent(FName Name){ return nullptr; }
FTransform AFGRainOcclusionActor::GenerateLocation(const FSimpleComponentInfo& componentInfo, const EFGRainOcclusionShape& shape){ return FTransform(); }
void FFGBuildingGatheringWorker::DoWork(){ }
