// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSignPixelInstanceManager.h"

UFGSignPixelInstanceManager::UFGSignPixelInstanceManager(){ }
void UFGSignPixelInstanceManager::BeginPlay(){ }
FSignHandle UFGSignPixelInstanceManager::AddPixelSign( AFGBuildablePixelSign* pixelSign){ return FSignHandle(); }
void UFGSignPixelInstanceManager::RemovePixelSign(const FSignHandle& signHandle){ }
void UFGSignPixelInstanceManager::CreateHierarchicalInstancingComponent(UStaticMesh* staticMesh){ }
void UFGSignPixelInstanceManager::CreateInstancesForSign( AFGBuildablePixelSign* pixelSign){ }
void UFGSignPixelInstanceManager::SetColorDataForPixelIndex(FSignHandle& signHandle, int32 pixelIndex, FLinearColor& newColor){ }
