// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSignSettings.h"

UFGSignSettings::UFGSignSettings(){ }
UFGSignSettings* UFGSignSettings::Get(){ return nullptr; }
FString UFGSignSettings::GetStringKeyFromAttributeTag(SignTags::AttributeTag tag) const{ return FString(); }
FString UFGSignSettings::GetStringKeyFromElementClass(TSubclassOf<UWidget> widgetClass) const{ return FString(); }
