// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSignTypes.h"

UFGSignTypeDescriptor::UFGSignTypeDescriptor(){ }
uint32 FPrefabSignData::GetGUID() const{ return uint32(); }
