// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSoundSplineComponent.h"

UFGSoundSplineComponent::UFGSoundSplineComponent(const  FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGSoundSplineComponent::Activate(bool reset){ }
void UFGSoundSplineComponent::SetAutoActivate(bool newAutoActivate){ }
void UFGSoundSplineComponent::SetEmitterInterval(float newEmitterInterval){ }
void UFGSoundSplineComponent::UpdateGameObjectPosition(){ }
