// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGTrainSoundComponent.h"

UFGTrainSoundComponent::UFGTrainSoundComponent(){ }
void UFGTrainSoundComponent::OnRegister(){ Super::OnRegister(); }
void UFGTrainSoundComponent::OnUnregister(){ Super::OnUnregister(); }
void UFGTrainSoundComponent::TickComponent(float dt, ELevelTick tickType, FActorComponentTickFunction* thisTickFunction){ }
void UFGTrainSoundComponent::RestartSounds_Implementation(){ }
void UFGTrainSoundComponent::UpdateAudioPositions(){ }
void UFGTrainSoundComponent::UpdateSmoothedTrainStats(float dt){ }
void UFGTrainSoundComponent::UpdateRTPCs(){ }
void UFGTrainSoundComponent::UpdateTriggers(){ }
