// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWorldSettings.h"

#if WITH_EDITOR
void AFGWorldSettings::CheckForErrors(){ Super::CheckForErrors(); }
void AFGWorldSettings::PostEditChangeProperty( FPropertyChangedEvent& propertyChangedEvent){ Super::PostEditChangeProperty(propertyChangedEvent); }
#endif 
#if WITH_EDITOR
void AFGWorldSettings::HandleMapChanged( UWorld* newWorld, EMapChangeType mapChangeType){ }
#endif 
#if WITH_EDITORONLY_DATA
#endif 
#if WITH_EDITOR
#endif 
#if WITH_EDITORONLY_DATA
#endif 
AFGWorldSettings::AFGWorldSettings(){ }
void AFGWorldSettings::BeginDestroy(){ Super::BeginDestroy(); }
void AFGWorldSettings::Serialize(FArchive& ar){ Super::Serialize(ar); }
void AFGWorldSettings::PostLoad(){ Super::PostLoad(); }
void AFGWorldSettings::PreInitializeComponents(){ Super::PreInitializeComponents(); }
void AFGWorldSettings::NotifyBeginPlay(){ Super::NotifyBeginPlay(); }
void AFGWorldSettings::PreSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGWorldSettings::PostSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGWorldSettings::PreLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGWorldSettings::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGWorldSettings::GatherDependencies_Implementation(TArray< UObject* >& out_dependentObjects){ }
bool AFGWorldSettings::NeedTransform_Implementation(){ return bool(); }
bool AFGWorldSettings::ShouldSave_Implementation() const{ return bool(); }
AExponentialHeightFog* AFGWorldSettings::GetExponentialHeightFog() const{ return nullptr; }
ASkyAtmosphere* AFGWorldSettings::GetSkyAtmosphere() const{ return nullptr; }
AFGSkySphere* AFGWorldSettings::GetSkySphere() const{ return nullptr; }
void AFGWorldSettings::UpdateWorldBounds(){ }
