// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWorldPartitionContentBundle.h"

#if WITH_EDITOR
void UFGWorldPartitionContentBundle::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent){ Super::PostEditChangeProperty(PropertyChangedEvent); }
#endif 
UFGWorldPartitionContentBundle::UFGWorldPartitionContentBundle(){ }
void UFGWorldPartitionContentBundle::BeginDestroy(){ Super::BeginDestroy(); }
