// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableWall.h"

AFGBuildableWall::AFGBuildableWall(){ }
void AFGBuildableWall::CalculateLocalSnapOffset(FVector& out_upVector, float& out_length) const{ }
