// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableRailroadSignal.h"

AFGBuildableRailroadSignal::AFGBuildableRailroadSignal(){ }
void AFGBuildableRailroadSignal::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBuildableRailroadSignal::BeginPlay(){ }
void AFGBuildableRailroadSignal::EndPlay(const EEndPlayReason::Type endPlayReason){ }
void AFGBuildableRailroadSignal::Destroyed(){ }
void AFGBuildableRailroadSignal::OnBuildEffectFinished(){ }
void AFGBuildableRailroadSignal::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGBuildableRailroadSignal::GainedSignificance_Implementation(){ }
void AFGBuildableRailroadSignal::LostSignificance_Implementation(){ }
void AFGBuildableRailroadSignal::GainedSignificance_Native(){ }
void AFGBuildableRailroadSignal::LostSignificance_Native(){ }
void AFGBuildableRailroadSignal::SetupForSignificance(){ }
void AFGBuildableRailroadSignal::PreUpgrade_Implementation(){ }
void AFGBuildableRailroadSignal::OnAspectChanged(){ }
void AFGBuildableRailroadSignal::OnBlockValidationChanged(){ }
void AFGBuildableRailroadSignal::OnDirectionalityChanged(){ }
void AFGBuildableRailroadSignal::DisconnectSignal(){ }
void AFGBuildableRailroadSignal::UpdateVisuals(){ }
void AFGBuildableRailroadSignal::ApplyVisualState(int16 state){ }
void AFGBuildableRailroadSignal::AddGuardedConnection( UFGRailroadTrackConnectionComponent* connection){ }
void AFGBuildableRailroadSignal::AddObservedConnection( UFGRailroadTrackConnectionComponent* connection){ }
void AFGBuildableRailroadSignal::UpdateConnections(){ }
void AFGBuildableRailroadSignal::SetObservedBlock(TWeakPtr< FFGRailroadSignalBlock > block){ }
void AFGBuildableRailroadSignal::OnBlockChanged(){ }
void AFGBuildableRailroadSignal::OnRep_Aspect(){ }
void AFGBuildableRailroadSignal::OnRep_BlockValidation(){ }
void AFGBuildableRailroadSignal::OnRep_VisualState(){ }
void AFGBuildableRailroadSignal::UpdateDirectionality(){ }
void AFGBuildableRailroadSignal::UpdateAspect(){ }
void AFGBuildableRailroadSignal::UpdateBlockValidation(){ }
