// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableRamp.h"

AFGBuildableRamp::AFGBuildableRamp(){ }
void AFGBuildableRamp::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
float AFGBuildableRamp::CalculateRampAngle() const{ return float(); }
