// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableWall.h"

AFGBuildableWall::AFGBuildableWall(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void AFGBuildableWall::CalculateLocalSnapOffset(FVector& out_upVector, float& out_length) const{ }
AFGBuildableWallLightweight::AFGBuildableWallLightweight(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
