// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableControlPanelHost.h"

AFGBuildableControlPanelHost::AFGBuildableControlPanelHost(){ }
void AFGBuildableControlPanelHost::BeginPlay(){ }
TArray< AFGBuildable* >& AFGBuildableControlPanelHost::GetControlledBuildables(TSubclassOf< AFGBuildable > outputType){ return *(new TArray< AFGBuildable* >); }
void AFGBuildableControlPanelHost::OnCircuitsChanged(){ }
void AFGBuildableControlPanelHost::SearchDownstreamCircuit(){ }
