// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableWalkway.h"

AFGBuildableWalkway::AFGBuildableWalkway(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
AFGBuildableWalkwayLightweight::AFGBuildableWalkwayLightweight(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
