// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableGeneratorNuclear.h"

AFGBuildableGeneratorNuclear::AFGBuildableGeneratorNuclear(){ }
void AFGBuildableGeneratorNuclear::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildableGeneratorNuclear::BeginPlay(){ }
void AFGBuildableGeneratorNuclear::Factory_Tick(float dt){ }
void AFGBuildableGeneratorNuclear::OnRep_ReplicationDetailActor(){ }
bool AFGBuildableGeneratorNuclear::Factory_HasPower() const{ return bool(); }
bool AFGBuildableGeneratorNuclear::CanStartPowerProduction_Implementation() const{ return bool(); }
bool AFGBuildableGeneratorNuclear::CanLoadFuel() const{ return bool(); }
void AFGBuildableGeneratorNuclear::LoadFuel(){ }
void AFGBuildableGeneratorNuclear::OnReplicationDetailActorRemoved(){ }
AFGReplicationDetailActor_GeneratorNuclear* AFGBuildableGeneratorNuclear::GetCastRepDetailsActor() const{ return nullptr; }
bool AFGBuildableGeneratorNuclear::IsWasteFull() const{ return bool(); }
void AFGBuildableGeneratorNuclear::TryProduceWaste(){ }
bool AFGBuildableGeneratorNuclear::CanFitWasteOfNextFuelClass() const{ return bool(); }
