// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableFoundation.h"

AFGBuildableFoundation::AFGBuildableFoundation(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
AFGBuildableFoundationLightweight::AFGBuildableFoundationLightweight(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
