// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildablePassthroughBase.h"

AFGBuildablePassthroughBase::AFGBuildablePassthroughBase(){ }
void AFGBuildablePassthroughBase::BeginPlay(){ }
void AFGBuildablePassthroughBase::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
int32 AFGBuildablePassthroughBase::GetDismantleRefundReturnsMultiplier() const{ return int32(); }
bool AFGBuildablePassthroughBase::GetIsSoftClearance() const{ return bool(); }
void AFGBuildablePassthroughBase::GetIgnoredBuildablesForClearance(TArray< AFGBuildable* >& out_ignoredBuildables){ }
void AFGBuildablePassthroughBase::OverlapCheckFoundations(UWorld* world, const FVector& worldLocation, const FQuat& worldRotation, float thickness, TArray<class AFGBuildableFoundation*>& out_foundations) const{ }
