// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildablePassthrough.h"

AFGBuildablePassthrough::AFGBuildablePassthrough(){ }
void AFGBuildablePassthrough::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildablePassthrough::StartIsLookedAtForDismantle_Implementation( AFGCharacterPlayer* byCharacter){ }
void AFGBuildablePassthrough::StopIsLookedAtForDismantle_Implementation( AFGCharacterPlayer* byCharacter){ }
void AFGBuildablePassthrough::GetChildDismantleActors_Implementation(TArray< AActor* >& out_ChildDismantleActors) const{ }
bool AFGBuildablePassthrough::GetValidAttachDirection(FVector& out_validDir) const{ return bool(); }
void AFGBuildablePassthrough::SetTopSnappedConnection( UFGConnectionComponent* connection){ }
void AFGBuildablePassthrough::SetBottomSnappedConnection( UFGConnectionComponent* connection){ }
void AFGBuildablePassthrough::GetIgnoredBuildablesForClearance(TArray<AFGBuildable*>& out_ignoredBuildables){ }
void AFGBuildablePassthrough::OnAttachedBuildableDismantled( AFGBuildable* dismantledBuildable){ }
