// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePole.h"

AFGBuildablePole::AFGBuildablePole(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void AFGBuildablePole::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBuildablePole::BeginPlay(){ }
void AFGBuildablePole::SetPoleHeight(float height){ }
void AFGBuildablePole::SetupConnectionComponent(){ }
TArray<struct FInstanceData> AFGBuildablePole::GetActorLightweightInstanceData_Implementation(){ return TArray<struct FInstanceData>(); }
void AFGBuildablePole::SetupInstances_Native(bool bSpawnHidden){ }
const FName AFGBuildablePole::PoleMeshName = FName();
AFGBuildablePoleLightweight::AFGBuildablePoleLightweight(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
