// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildablePipeHyperAttachment.h"

AFGBuildablePipeHyperAttachment::AFGBuildablePipeHyperAttachment(){ }
void AFGBuildablePipeHyperAttachment::GetDismantleRefund_Implementation(TArray< FInventoryStack >& out_refund, bool noBuildCostEnabled) const{ }
