// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableSignSupport.h"

AFGBuildableSignSupport::AFGBuildableSignSupport(){ }
void AFGBuildableSignSupport::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBuildableSignSupport::BeginPlay(){ }
void AFGBuildableSignSupport::SetPoleScale(FVector2D poleScale){ }
const FName AFGBuildableSignSupport::PoleMeshName = FName();
