// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePoleBase.h"

bool AFGBuildablePoleBase::ShouldBeConsideredForBase_Implementation(){ return bool(); }
