// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePassthrough.h"

AFGBuildablePassthrough::AFGBuildablePassthrough(){ }
void AFGBuildablePassthrough::BeginPlay(){ }
void AFGBuildablePassthrough::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildablePassthrough::StartIsLookedAtForDismantle_Implementation( AFGCharacterPlayer* byCharacter){ }
void AFGBuildablePassthrough::StopIsLookedAtForDismantle_Implementation( AFGCharacterPlayer* byCharacter){ }
void AFGBuildablePassthrough::GetChildDismantleActors_Implementation(TArray< AActor* >& out_ChildDismantleActors) const{ }
void AFGBuildablePassthrough::GetIgnoredBuildablesForClearanceOnSnap(TArray< AFGBuildable* >& out_ignoredBuildables){ }
bool AFGBuildablePassthrough::GetValidAttachDirection(FVector& out_validDir){ return bool(); }
void AFGBuildablePassthrough::SetBottomSnappedConnection( UFGConnectionComponent* connection){ }
void AFGBuildablePassthrough::SetTopSnappedConnection( UFGConnectionComponent* connection){ }
void AFGBuildablePassthrough::OnAttachedBuildableDismantled( AFGBuildable* dismantledBuildable){ }
