// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableWaterPump.h"

AFGBuildableWaterPump::AFGBuildableWaterPump(){ }
AActor* AFGBuildableWaterPump::TryFindMissingResource(){ return nullptr; }
