// This file has been automatically generated by the Unreal Header Implementation tool

#include "Atmosphere/UFGBiome.h"

UFGBiome::UFGBiome(){ }
void UFGBiome::Serialize(FArchive& Ar){ Super::Serialize(Ar); }
