// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGListView.h"

TSharedRef<STableViewBase> UFGListView::RebuildListWidget() {
  return ConstructListView<SFGListView>();
}

UFGListView::UFGListView(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
