// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPlayerNameTagWidget.h"

void UFGPlayerNameTagWidget::UpdatePlayerData(FString playerName, FLinearColor playerColor, bool isPlayerOnline, bool useOverrideIcon){ }
void UFGPlayerNameTagWidget::NativeConstruct(){ }
void UFGPlayerNameTagWidget::OnHiddenHUDModeChanged(bool hideHUD){ }
