// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPlayerNameTagWidget.h"

void UFGPlayerNameTagWidget::UpdatePlayerData(FString playerName, FLinearColor playerColor, bool isPlayerOnline){ }
void UFGPlayerNameTagWidget::NativeConstruct(){ }
