// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGConsumablesConsumedDependency.h"

bool UFGConsumablesConsumedDependency::AreDependenciesMet(UObject* worldContext) const{ return bool(); }
