// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreaturesKilledDependency.h"

bool UFGCreaturesKilledDependency::AreDependenciesMet(UObject* worldContext) const{ return bool(); }
