// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGItemsManuallyCraftedDependency.h"

bool UFGItemsManuallyCraftedDependency::AreDependenciesMet(UObject* worldContext) const{ return bool(); }
