// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGAttachmentSplitterHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGAttachmentSplitterHologram::AFGAttachmentSplitterHologram(){ 
	this->mUpgradedSplitter = nullptr;
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGAttachmentSplitterHologram::BeginPlay(){ }
bool AFGAttachmentSplitterHologram::TryUpgrade(const FHitResult& hitResult){ return bool(); }
bool AFGAttachmentSplitterHologram::DoMultiStepPlacement(bool isInputFromARelease){ return bool(); }
AActor* AFGAttachmentSplitterHologram::GetUpgradedActor() const{ return nullptr; }
void AFGAttachmentSplitterHologram::ConfigureComponents( AFGBuildable* inBuildable) const{ }
