// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGCeilingLightHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGCeilingLightHologram::AFGCeilingLightHologram(){ 
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->mUseBuildClearanceOverlapSnapp = false;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGCeilingLightHologram::BeginPlay(){ }
bool AFGCeilingLightHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGCeilingLightHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
void AFGCeilingLightHologram::CheckValidFloor(){ }
void AFGCeilingLightHologram::CheckClearance(const FVector& locationOffset){ }
