// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGConveyorPoleHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGConveyorPoleHologram::AFGConveyorPoleHologram(){ 
	this->mSnapConnection = nullptr;
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->mUseBuildClearanceOverlapSnapp = false;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGConveyorPoleHologram::BeginPlay(){ }
void AFGConveyorPoleHologram::SnapToConnection(UFGFactoryConnectionComponent* connection,  AFGConveyorBeltHologram* parentConveyor){ }
void AFGConveyorPoleHologram::SetSnappBuilding( AFGBuildable* snappedBuilding){ }
