// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGFactoryHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGFactoryHologram::AFGFactoryHologram(){ 
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGFactoryHologram::BeginPlay(){ }
void AFGFactoryHologram::Tick(float dt){ }
void AFGFactoryHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
