// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGPassthroughHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGPassthroughHologram::AFGPassthroughHologram(){ 
	this->mAlignDirection.X = 0.0;
	this->mAlignDirection.Y = 0.0;
	this->mAlignDirection.Z = 0.0;
	this->mSnappedFoundation = nullptr;
	this->mSnappedBuildingThickness = 0.0;
	this->mMidMeshLength = 0.0;
	this->mCapMesh = nullptr;
	this->mMidMesh = nullptr;
	this->mEndCapRotation.Pitch = 0.0;
	this->mEndCapRotation.Yaw = 0.0;
	this->mEndCapRotation.Roll = 0.0;
	this->mMidMeshRotation.Pitch = 0.0;
	this->mMidMeshRotation.Yaw = 0.0;
	this->mMidMeshRotation.Roll = 0.0;
	this->mClearanceHeightMin = 0.0;
	this->mClearanceThickness = 0.0;
	this->mConnectionClass = nullptr;
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGPassthroughHologram::BeginPlay(){ }
void AFGPassthroughHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
bool AFGPassthroughHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGPassthroughHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
void AFGPassthroughHologram::BuildMeshes(){ }
void AFGPassthroughHologram::UpdateClearance(){ }
