// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGPowerPoleWallHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGPowerPoleWallHologram::AFGPowerPoleWallHologram(){ 
	this->mIsRotationAllowed = false;
	this->mCanSnapToFoundationCeiling = false;
	this->mCanSnapToFoundationSide = false;
	this->mCanSnapToBeams = false;
	this->mSnapOffset.X = 0.0;
	this->mSnapOffset.Y = 0.0;
	this->mFoundationSnappingInset = 0.0;
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGPowerPoleWallHologram::BeginPlay(){ }
bool AFGPowerPoleWallHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGPowerPoleWallHologram::CheckValidFloor(){ }
void AFGPowerPoleWallHologram::CheckClearance(const FVector& locationOffset){ }
