// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGRailroadBridgeHologram.h"
#include "Components/SplineComponent.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGRailroadBridgeHologram::AFGRailroadBridgeHologram(){ 
	this->mSnappedFoundation[0] = nullptr;
	this->mSnappedFoundation[1] = nullptr;
	this->mSplineComponent = CreateDefaultSubobject<USplineComponent>(TEXT("mSplineComponent"));
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mSplineComponent->SetupAttachment(RootComponent);
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGRailroadBridgeHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
bool AFGRailroadBridgeHologram::DoMultiStepPlacement(bool isInputFromARelease){ return bool(); }
void AFGRailroadBridgeHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
AFGBuildableFoundation* AFGRailroadBridgeHologram::FindOverlappingFoundation(const FVector& location, float radius) const{ return nullptr; }
