// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGSignPoleHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGSignPoleHologram::AFGSignPoleHologram(){ 
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->mUseBuildClearanceOverlapSnapp = false;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGSignPoleHologram::BeginPlay(){ }
bool AFGSignPoleHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGSignPoleHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
