// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGStairHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGStairHologram::AFGStairHologram(){ 
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGStairHologram::BeginPlay(){ }
bool AFGStairHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGStairHologram::CheckValidPlacement(){ }
bool AFGStairHologram::IsHologramIdenticalToBuildable( AFGBuildable* buildable, const FVector& hologramLocationOffset) const{ return bool(); }
