// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGStackableStorageHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGStackableStorageHologram::AFGStackableStorageHologram(){ 
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGStackableStorageHologram::BeginPlay(){ }
bool AFGStackableStorageHologram::IsValidHitResult(const FHitResult& hitResult) const{ return bool(); }
bool AFGStackableStorageHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
int32 AFGStackableStorageHologram::GetRotationStep() const{ return int32(); }
