// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGVehicleHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGVehicleHologram::AFGVehicleHologram(){ 
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->mSoftClearanceOverlapResponse = EHologramSoftClearanceResponse::HSCR_Block;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
void AFGVehicleHologram::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGVehicleHologram::BeginPlay(){ }
AActor* AFGVehicleHologram::Construct(TArray< AActor* >& out_children, FNetConstructionID netConstructionID){ return nullptr; }
void AFGVehicleHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
void AFGVehicleHologram::CheckValidPlacement(){ }
AFGVehicle* AFGVehicleHologram::ConstructVehicle(FNetConstructionID netConstructionID) const{ return nullptr; }
