// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGWallAttachmentHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGWallAttachmentHologram::AFGWallAttachmentHologram(){ 
	this->mCanSnapToFoundationFloor = false;
	this->mCanSnapToWalls = true;
	this->mSnapAxis = EAxis::X;
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
bool AFGWallAttachmentHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGWallAttachmentHologram::CheckValidFloor(){ }
void AFGWallAttachmentHologram::CheckClearance(const FVector& locationOffset){ }
