// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGWalkwayHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGWalkwayHologram::AFGWalkwayHologram(){ 
	this->mOnlyAllowLineZoop = false;
	this->mPlacementRequirements = EFactoryBuildingPlacementRequirements::FBPR_MustSnap;
	this->mLoopSound = CreateDefaultSubobject<UAkComponent>(TEXT("LoopSound"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mLoopSound->SetupAttachment(RootComponent);
}
bool AFGWalkwayHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGWalkwayHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
void AFGWalkwayHologram::CheckValidPlacement(){ }
void AFGWalkwayHologram::UpdateZoop(){ }
void AFGWalkwayHologram::ConstructZoop(TArray<AActor*>& out_children){ }
FVector AFGWalkwayHologram::ConvertZoopToWorldLocation(const FIntVector& zoop) const{ return FVector(); }
void AFGWalkwayHologram::BeginPlay(){ }
