// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBlueprintDesignerHologram.h"

void AFGBlueprintDesignerHologram::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBlueprintDesignerHologram::HandleClearanceOverlap(const FOverlapResult& overlap, const FVector& locationOffset, bool HologramHasSoftClearance){ }
void AFGBlueprintDesignerHologram::SpawnChildren(AActor* hologramOwner, FVector spawnLocation, APawn* hologramInstigator){ }
AActor* AFGBlueprintDesignerHologram::Construct(TArray< AActor* >& out_children, FNetConstructionID netConstructionID){ return nullptr; }
USceneComponent* AFGBlueprintDesignerHologram::SetupComponent(USceneComponent* attachParent, UActorComponent* componentTemplate, const FName& componentName, const FName& attachSocketName){ return nullptr; }
void AFGBlueprintDesignerHologram::OnHologramTransformUpdated(){ }
void AFGBlueprintDesignerHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
