// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCornerWallHologram.h"

AFGCornerWallHologram::AFGCornerWallHologram(){ }
void AFGCornerWallHologram::BeginPlay(){ }
bool AFGCornerWallHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
