// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGFactoryHologram.h"

AFGFactoryHologram::AFGFactoryHologram(){ }
void AFGFactoryHologram::BeginPlay(){ }
void AFGFactoryHologram::Tick(float dt){ }
void AFGFactoryHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
