// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGGeoThermalGeneratorHologram.h"

void AFGGeoThermalGeneratorHologram::BeginPlay(){ }
void AFGGeoThermalGeneratorHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
bool AFGGeoThermalGeneratorHologram::CanOccupyResource(const TScriptInterface<  IFGExtractableResourceInterface >& resource) const{ return bool(); }
