// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPassthroughHologram.h"

AFGPassthroughHologram::AFGPassthroughHologram(){ }
void AFGPassthroughHologram::BeginPlay(){ }
void AFGPassthroughHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
bool AFGPassthroughHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGPassthroughHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
void AFGPassthroughHologram::BuildMeshes(){ }
void AFGPassthroughHologram::UpdateClearance(){ }
