// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGPassthroughPipeBaseHologram.h"

AFGPassthroughPipeBaseHologram::AFGPassthroughPipeBaseHologram(){ }
void AFGPassthroughPipeBaseHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
void AFGPassthroughPipeBaseHologram::RebuildMeshesAndUpdateClearance(){ }
