// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPoleHologram.h"

AFGPoleHologram::AFGPoleHologram(){ }
void AFGPoleHologram::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGPoleHologram::BeginPlay(){ }
bool AFGPoleHologram::DoMultiStepPlacement(bool isInputFromARelease){ return bool(); }
bool AFGPoleHologram::IsValidHitResult(const FHitResult& hitResult) const{ return bool(); }
bool AFGPoleHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGPoleHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
AActor* AFGPoleHologram::Construct(TArray<AActor*>& out_children, FNetConstructionID constructionID){ return nullptr; }
void AFGPoleHologram::GetSupportedBuildModes_Implementation(TArray< TSubclassOf< UFGBuildGunModeDescriptor > >& out_buildmodes) const{ }
void AFGPoleHologram::OnBuildModeChanged(TSubclassOf<UFGHologramBuildModeDescriptor> buildMode){ }
int32 AFGPoleHologram::GetBaseCostMultiplier() const{ return int32(); }
bool AFGPoleHologram::CanNudgeHologram() const{ return bool(); }
void AFGPoleHologram::ResetBuildSteps(){ }
void AFGPoleHologram::SetPoleHeight(float height){ }
void AFGPoleHologram::SerializeConstructMessage(FArchive& ar, FNetConstructionID id){ }
void AFGPoleHologram::ServerPostConstructMessageDeserialization(){ }
void AFGPoleHologram::OnConstructMessagedDeserialized_Implementation(){ }
void AFGPoleHologram::OnPendingConstructionHologramCreated_Implementation( AFGHologram* fromHologram){ }
float AFGPoleHologram::GetActiveMeshHeight() const{ return float(); }
void AFGPoleHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
void AFGPoleHologram::CheckValidPlacement(){ }
void AFGPoleHologram::OnRep_PoleMesh(){ }
void AFGPoleHologram::UpdatePoleHeightRelativeLoc(){ }
