// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPowerPoleWallHologram.h"

AFGPowerPoleWallHologram::AFGPowerPoleWallHologram(){ }
void AFGPowerPoleWallHologram::BeginPlay(){ }
bool AFGPowerPoleWallHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGPowerPoleWallHologram::CheckValidFloor(){ }
void AFGPowerPoleWallHologram::CheckClearance(const FVector& locationOffset){ }
