// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGRailroadSignalHologram.h"

AFGRailroadSignalHologram::AFGRailroadSignalHologram(){ }
void AFGRailroadSignalHologram::BeginPlay(){ }
void AFGRailroadSignalHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
void AFGRailroadSignalHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
void AFGRailroadSignalHologram::CheckValidPlacement(){ }
