// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGRoadHologram.h"

AFGRoadHologram::AFGRoadHologram(){ }
void AFGRoadHologram::BeginPlay(){ }
USceneComponent* AFGRoadHologram::SetupComponent(USceneComponent* attachParent, UActorComponent* componentTemplate, const FName& componentName, const FName& attachSocketName){ return nullptr; }
void AFGRoadHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
bool AFGRoadHologram::DoMultiStepPlacement(bool isInputFromARelease){ return bool(); }
void AFGRoadHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
void AFGRoadHologram::ConfigureComponents( AFGBuildable* inBuildable) const{ }
void AFGRoadHologram::CheckValidFloor(){ }
void AFGRoadHologram::CheckClearance(const FVector& locationOffset){ }
UFGRoadConnectionComponent* AFGRoadHologram::FindOverlappingConnectionComponent(const FVector& location, float radius,  UFGRoadConnectionComponent* ignoredConnection, bool ignoreIsConnected) const{ return nullptr; }
