// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSignPoleHologram.h"

AFGSignPoleHologram::AFGSignPoleHologram(){ }
void AFGSignPoleHologram::BeginPlay(){ }
bool AFGSignPoleHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGSignPoleHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
