// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGStairHologram.h"

AFGStairHologram::AFGStairHologram(){ }
void AFGStairHologram::BeginPlay(){ }
bool AFGStairHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGStairHologram::CheckValidPlacement(){ }
bool AFGStairHologram::IsHologramIdenticalToBuildable( AFGBuildable* buildable, const FVector& hologramLocationOffset) const{ return bool(); }
