// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGStairHologram.h"

AFGStairHologram::AFGStairHologram(){ }
void AFGStairHologram::BeginPlay(){ }
bool AFGStairHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGStairHologram::AdjustForGround(FVector& out_adjustedLocation, FRotator& out_adjustedRotation){ }
void AFGStairHologram::CheckValidPlacement(){ }
bool AFGStairHologram::IsHologramIdenticalToActor(AActor* actor, const FVector& hologramLocationOffset) const{ return bool(); }
