// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWalkwayHologram.h"

AFGWalkwayHologram::AFGWalkwayHologram() : Super() {
	this->mMaxPlacementFloorAngle = 35;
	this->mValidHitClasses.Add(AFGBuildableFoundation::StaticClass()); this->mValidHitClasses.Add(AFGBuildableRailroadTrack::StaticClass()); this->mValidHitClasses.Add(AFGBuildableRoad::StaticClass()); this->mValidHitClasses.Add(AFGBuildableFoundation::StaticClass()); this->mValidHitClasses.Add(AFGBuildableWalkway::StaticClass());
	this->mUseBuildClearanceOverlapSnapp = true;
	this->SetHidden(true);
	this->SetReplicates(true);
}
bool AFGWalkwayHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGWalkwayHologram::BeginPlay(){ }
