// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGWallAttachmentHologram.h"

AFGWallAttachmentHologram::AFGWallAttachmentHologram(){ }
bool AFGWallAttachmentHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGWallAttachmentHologram::CheckValidFloor(){ }
