// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWalkwayHologram.h"

AFGWalkwayHologram::AFGWalkwayHologram(){ }
bool AFGWalkwayHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
void AFGWalkwayHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
void AFGWalkwayHologram::CheckValidPlacement(){ }
void AFGWalkwayHologram::UpdateZoop(){ }
void AFGWalkwayHologram::ConstructZoop(TArray<AActor*>& out_children){ }
FVector AFGWalkwayHologram::ConvertZoopToWorldLocation(const FIntVector& zoop) const{ return FVector(); }
void AFGWalkwayHologram::BeginPlay(){ }
