// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableResourceSinkShop.h"
#include "Hologram/FGFactoryHologram.h"
#include "FGPowerInfoComponent.h"
#include "Components/SceneComponent.h"

AFGBuildableResourceSinkShop::AFGBuildableResourceSinkShop(){ 
	this->mShopInventory = nullptr;
	this->mShopInventoryDefaultSize = 30;
	this->mPowerInfoClass = UFGPowerInfoComponent::StaticClass();
	this->mHologramClass = AFGFactoryHologram::StaticClass();
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
}
void AFGBuildableResourceSinkShop::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildableResourceSinkShop::BeginPlay(){ }
void AFGBuildableResourceSinkShop::OnReplicationDetailActorCreated(){ }
void AFGBuildableResourceSinkShop::OnReplicationDetailActorRemoved(){ }
bool AFGBuildableResourceSinkShop::CanInventoryFitPlannedPurchase(TArray< TSubclassOf<  UFGSchematic > > schematics) const{ return bool(); }
bool AFGBuildableResourceSinkShop::PurchaseResourceSinkSchematics( UFGInventoryComponent* playerInventory, TArray< TSubclassOf<  UFGSchematic > > schematics){ return bool(); }
