// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableControlPanelHost.h"
#include "Components/SceneComponent.h"

AFGBuildableControlPanelHost::AFGBuildableControlPanelHost(){ 
	this->mDownstreamConnection = nullptr;
	this->mControlledBuildableType = nullptr;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
}
void AFGBuildableControlPanelHost::BeginPlay(){ }
TArray< AFGBuildable* >& AFGBuildableControlPanelHost::GetControlledBuildables(TSubclassOf< AFGBuildable > outputType){ return *(new TArray< AFGBuildable* >); }
void AFGBuildableControlPanelHost::OnCircuitsChanged(){ }
void AFGBuildableControlPanelHost::SearchDownstreamCircuit(){ }
