// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableWaterPump.h"
#include "FGConstructDisqualifier.h"
#include "FGPowerInfoComponent.h"
#include "Components/SceneComponent.h"
#include "Hologram/FGResourceExtractorHologram.h"

AFGBuildableWaterPump::AFGBuildableWaterPump(){ 
	this->mMinimumDepthForPlacement = 0.0;
	this->mDepthTraceOriginOffset.X = 0.0;
	this->mDepthTraceOriginOffset.Y = 0.0;
	this->mDepthTraceOriginOffset.Z = 0.0;
	this->mMustPlaceOnResourceDisqualifier = UFGCDNeedsResourceNode::StaticClass();
	this->mPowerInfoClass = UFGPowerInfoComponent::StaticClass();
	this->mHologramClass = AFGResourceExtractorHologram::StaticClass();
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
}
AActor* AFGBuildableWaterPump::TryFindMissingResource(){ return nullptr; }
