// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableRailroadBridge.h"
#include "FGSplineComponent.h"
#include "Components/SceneComponent.h"

AFGBuildableRailroadBridge::AFGBuildableRailroadBridge(){ 
	this->mSplineComponent = CreateDefaultSubobject<UFGSplineComponent>(TEXT("SplineComponent"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mSplineComponent->SetupAttachment(RootComponent);
}
void AFGBuildableRailroadBridge::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildableRailroadBridge::BeginPlay(){ }
