// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableDecor.h"
#include "Hologram/FGDecorHologram.h"
#include "Components/SceneComponent.h"

void AFGBuildableDecor::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
AFGBuildableDecor::AFGBuildableDecor(){ 
	this->mDecorMesh = nullptr;
	this->mHologramClass = AFGDecorHologram::StaticClass();
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
}
