// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableAttachmentMerger.h"
#include "Components/SceneComponent.h"
#include "Hologram/FGConveyorAttachmentHologram.h"

AFGBuildableAttachmentMerger::AFGBuildableAttachmentMerger(){ 
	this->mCurrentInputIndex = -1;
	this->mCurrentInventoryIndex = 0;
	this->mPowerInfoClass = nullptr;
	this->mMinimumProducingTime = -1.0;
	this->mMinimumStoppedTime = -1.0;
	this->mHologramClass = AFGConveyorAttachmentHologram::StaticClass();
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
}
void AFGBuildableAttachmentMerger::BeginPlay(){ }
void AFGBuildableAttachmentMerger::Factory_Tick(float deltaTime){ }
void AFGBuildableAttachmentMerger::Factory_CollectInput_Implementation(){ }
bool AFGBuildableAttachmentMerger::Factory_GrabOutput_Implementation( UFGFactoryConnectionComponent* connection, FInventoryItem& out_item, float& out_OffsetBeyond, TSubclassOf< UFGItemDescriptor > type){ return bool(); }
