// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildablePipeHyper.h"
#include "Components/SplineComponent.h"
#include "FGInstancedSplineMeshComponent.h"
#include "FGPipeConnectionComponentHyper.h"
#include "Components/SceneComponent.h"

AFGBuildablePipeHyper::AFGBuildablePipeHyper(){ 
	this->mConnection0 = CreateDefaultSubobject<UFGPipeConnectionComponentHyper>(TEXT("PipeHyperConnection0"));
	this->mConnection1 = CreateDefaultSubobject<UFGPipeConnectionComponentHyper>(TEXT("PipeHyperConnection1"));
	this->mSplineComponent = CreateDefaultSubobject<USplineComponent>(TEXT("SplineComponent"));
	this->mInstancedSplineComponent = CreateDefaultSubobject<UFGInstancedSplineMeshComponent>(TEXT("InstancedSplineComponent"));
	this->NetDormancy = ENetDormancy::DORM_Initial;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mConnection0->SetupAttachment(RootComponent);
	this->mConnection1->SetupAttachment(RootComponent);
	this->mSplineComponent->SetupAttachment(RootComponent);
	this->mInstancedSplineComponent->SetupAttachment(RootComponent);
}
void AFGBuildablePipeHyper::BeginPlay(){ }
float AFGBuildablePipeHyper::GetPipeProgressOfConnection_Implementation(const UFGPipeConnectionComponentBase* connectionEnteredThrough){ return float(); }
void AFGBuildablePipeHyper::OnPipeMove_Implementation(UFGCharacterMovementComponent* charMove, float deltaTime){ }
UFGPipeConnectionComponentBase* AFGBuildablePipeHyper::GetEndOfPipeInDirectionAndMaxDist(const UFGPipeConnectionComponentBase* enterFromConnection, float maxDist, float& distSoFar) const{ return nullptr; }
bool AFGBuildablePipeHyper::OnPipeEnter_Implementation(UFGCharacterMovementComponent* charMove, const UFGPipeConnectionComponentBase* connectionEnteredThrough , const AActor* fromPipe){ return bool(); }
const FName AFGBuildablePipeHyper::mConnectionName0 = FName();
const FName AFGBuildablePipeHyper::mConnectionName1 = FName();
