// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableWalkway.h"
#include "Components/SceneComponent.h"
#include "FGColoredInstanceMeshProxy.h"
#include "Hologram/FGWalkwayHologram.h"

AFGBuildableWalkway::AFGBuildableWalkway(){ 
	this->mSize = 200.0;
	this->mElevation = 0.0;
	this->mDisableSnapOn.Front = false;
	this->mDisableSnapOn.Right = false;
	this->mDisableSnapOn.Back = false;
	this->mDisableSnapOn.Left = false;
	this->mDisableSnapOn.Top = true;
	this->mDisableSnapOn.Bottom = true;
	this->mMeshComponentProxy = CreateDefaultSubobject<UFGColoredInstanceMeshProxy>(TEXT("BuildingMeshProxy"));
	this->mHologramClass = AFGWalkwayHologram::StaticClass();
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mMeshComponentProxy->SetupAttachment(RootComponent);
}
