// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableStair.h"
#include "Components/SceneComponent.h"
#include "FGColoredInstanceMeshProxy.h"
#include "Hologram/FGStairHologram.h"

AFGBuildableStair::AFGBuildableStair(){ 
	this->mStairDirection = EBuildableStairDirection::EBSD_Right;
	this->mHeight = 0.0;
	this->mSize = 0.0;
	this->mMeshComponentProxy = CreateDefaultSubobject<UFGColoredInstanceMeshProxy>(TEXT("BuildingMeshProxy"));
	this->mHologramClass = AFGStairHologram::StaticClass();
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mMeshComponentProxy->SetupAttachment(RootComponent);
}
