// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGConveyorPoleStackable.h"
#include "FGFactoryConnectionComponent.h"
#include "Components/SceneComponent.h"
#include "FGColoredInstanceMeshProxy.h"
#include "Hologram/FGPoleHologram.h"

AFGConveyorPoleStackable::AFGConveyorPoleStackable(){ 
	this->mPoleComponentProxy = CreateDefaultSubobject<UFGColoredInstanceMeshProxy>(TEXT("PoleComponentProxy"));
	this->mSnapOnly0 = CreateDefaultSubobject<UFGFactoryConnectionComponent>(TEXT("SnapOnly0"));
	this->mHologramClass = AFGPoleHologram::StaticClass();
	this->mCreateClearanceMeshRepresentation = false;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mPoleComponentProxy->SetupAttachment(RootComponent);
	this->mSnapOnly0->SetupAttachment(RootComponent);
}
void AFGConveyorPoleStackable::SetupConnectionComponent(){ }
