// This file has been automatically generated by the Unreal Header Implementation tool

#include "UI/FGListView.h"

UFGListView::UFGListView(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
	this->mWidgetBarStyle.Thickness = 8.0;
}
TSharedRef<STableViewBase> UFGListView::RebuildListWidget(){ return Super::RebuildListWidget(); }
