// This file has been automatically generated by the Unreal Header Implementation tool

#include "FactoryGame.h"
#include "Modules/ModuleManager.h"

DEFINE_LOG_CATEGORY(LogGame);

IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl, FactoryGame, "FactoryGame");