// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAttachmentPointComponent.h"

UFGAttachmentPointComponent::UFGAttachmentPointComponent(){ 
	this->mUsage = EAttachmentPointUsage::EAPU_Default;
	this->mType = nullptr;
}
