// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePipePart.h"
#include "FGPowerInfoComponent.h"
#include "Components/SceneComponent.h"
#include "FGColoredInstanceMeshProxy.h"
#include "FGBuildablePipePart.h"

#if WITH_EDITOR
void AFGBuildablePipePart::OnConstruction(const FTransform& transform){ }
#endif 
AFGBuildablePipePart::AFGBuildablePipePart(){ 
	this->mLength = 200.0;
	this->mCanStack = false;
	this->mStackHeight = 0.0;
	this->mSupportComponentDefaultMesh = CreateDefaultSubobject<UFGColoredInstanceMeshProxy>(TEXT("SupportMeshCompProxyHolder"));
	this->mConnection0 = nullptr;
	this->mSupportMesh = nullptr;
	this->mUseStaticHeight = false;
	this->mPowerInfoClass = UFGPowerInfoComponent::StaticClass();
	this->mHologramClass = AFGBuildablePipePart::StaticClass();
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mSupportComponentDefaultMesh->SetupAttachment(RootComponent);
}
void AFGBuildablePipePart::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBuildablePipePart::BeginPlay(){ }
void AFGBuildablePipePart::SetSupportLength(float length){ }
void AFGBuildablePipePart::SetupConnectionComponent(){ }
const FName AFGBuildablePipePart::SupportMeshName = FName();
float AFGBuildablePipeHyperPart::GetPipeProgressOfConnection_Implementation(const UFGPipeConnectionComponentBase* connectionEnteredThrough){ return float(); }
void AFGBuildablePipeHyperPart::OnPipeMove_Implementation(UFGCharacterMovementComponent* charMove, float deltaTime){ }
bool AFGBuildablePipeHyperPart::OnPipeEnter_Implementation(UFGCharacterMovementComponent* charMove, const UFGPipeConnectionComponentBase* connectionEnteredThrough , const AActor* fromPipe){ return bool(); }
