// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePillar.h"
#include "Components/SceneComponent.h"
#include "FGColoredInstanceMeshProxy.h"

AFGBuildablePillar::AFGBuildablePillar(){ 
	this->mSize.X = 0.0;
	this->mSize.Y = 0.0;
	this->mSize.Z = 0.0;
	this->mMeshComponentProxy = CreateDefaultSubobject<UFGColoredInstanceMeshProxy>(TEXT("BuildingMeshProxy"));
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mMeshComponentProxy->SetupAttachment(RootComponent);
}
