// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGClearanceComponent.h"
#include "NavAreas/NavArea_Obstacle.h"

UFGClearanceComponent::UFGClearanceComponent(){ 
	this->mIsSoftClearance = false;
	this->AreaClass = UNavArea_Obstacle::StaticClass();
	this->Mobility = EComponentMobility::Static;
}
UFGComplexClearanceComponent::UFGComplexClearanceComponent(){ 
	this->Mobility = EComponentMobility::Static;
}
