// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGConveyorInstanceMeshBucket.h"

UFGConveyorInstanceMeshBucket::UFGConveyorInstanceMeshBucket(){ 
	this->mNumInstances = 32;
	this->bCanEverAffectNavigation = false;
}
void UFGConveyorInstanceMeshBucket::Init(){ }
void UFGConveyorInstanceMeshBucket::DirectUpdateInstance(const TArray<FTransform> &Transforms){ }
FBoxSphereBounds UFGConveyorInstanceMeshBucket::CalcBounds(const FTransform& LocalToWorld) const{ return FBoxSphereBounds(); }
