// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCrashSiteDebrisActor.h"
#include "Components/StaticMeshComponent.h"

AFGCrashSiteDebrisActor::AFGCrashSiteDebrisActor(){ 
	this->mMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	this->RootComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
}
void AFGCrashSiteDebrisActor::BeginPlay(){ }
void AFGCrashSiteDebrisActor::EndPlay(const EEndPlayReason::Type endPlayReason){ }
void AFGCrashSiteDebrisActor::GainedSignificance_Implementation(){ }
void AFGCrashSiteDebrisActor::LostSignificance_Implementation(){ }
