// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCrashSiteDebrisActor.h"
#include "Components/HierarchicalInstancedStaticMeshComponent.h"

AFGCrashSiteDebrisActor::AFGCrashSiteDebrisActor() : Super() {
	this->mMesh = CreateDefaultSubobject<UHierarchicalInstancedStaticMeshComponent>(TEXT("Mesh"));
	this->RootComponent = CreateDefaultSubobject<UHierarchicalInstancedStaticMeshComponent>(TEXT("Mesh"));
}
void AFGCrashSiteDebrisActor::BeginPlay(){ }
void AFGCrashSiteDebrisActor::EndPlay(const EEndPlayReason::Type endPlayReason){ }
void AFGCrashSiteDebrisActor::GainedSignificance_Implementation(){ }
void AFGCrashSiteDebrisActor::LostSignificance_Implementation(){ }
