// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGDamageOverTimeVolume.h"
#include "Components/BrushComponent.h"
#include "FGDotComponent.h"

#if WITH_EDITOR
void AFGDamageOverTimeVolume::CheckForErrors(){ Super::CheckForErrors(); }
#endif 
AFGDamageOverTimeVolume::AFGDamageOverTimeVolume(){ 
	this->mPostProcessSettings = nullptr;
	this->mDotComponent = CreateDefaultSubobject<UFGDotComponent>(TEXT("DotComponent"));
	this->RootComponent = CreateDefaultSubobject<UBrushComponent>(TEXT("BrushComponent0"));
}
bool AFGDamageOverTimeVolume::EncompassesPoint(FVector point, float sphereRadius , float* out_distanceToPoint){ return bool(); }
FPostProcessVolumeProperties AFGDamageOverTimeVolume::GetProperties() const{ return FPostProcessVolumeProperties(); }
void AFGDamageOverTimeVolume::PostUnregisterAllComponents(void){ }
void AFGDamageOverTimeVolume::PostRegisterAllComponents(){ }
