// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFluidIntegrantInterface.h"

bool FFluidBox::Serialize(FArchive& ar){ return bool(); }
bool FFluidBox::operator==(const FFluidBox& other) const{ return bool(); }
bool FFluidBox::operator!=(const FFluidBox& other) const{ return bool(); }
float FFluidBox::OVERFILL_USED_FOR_PRESSURE_PCT = float();
float FFluidBox::PRESSURE_LOSS = float();
void IFGFluidIntegrantInterface::OnFluidDescriptorSet(){ }
