// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPassengerSeat.h"
#include "AIController.h"

void AFGPassengerSeat::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
AFGPassengerSeat::AFGPassengerSeat(){ 
	this->mOuterVehicle = nullptr;
	this->AIControllerClass = AAIController::StaticClass();
}
void AFGPassengerSeat::Tick(float dt){ }
