// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPlayerStartTradingPost.h"
#include "Components/CapsuleComponent.h"

AFGPlayerStartTradingPost::AFGPlayerStartTradingPost(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { 
	this->PlayerStartTag = TEXT("TRADING_POST");
	this->RootComponent = CreateDefaultSubobject<UCapsuleComponent>(TEXT("CollisionCapsule"));
}
const FName AFGPlayerStartTradingPost::STATIC_PLAYER_START_TAG = FName();
