// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGRecipe.h"

#if WITH_EDITOR
bool UFGRecipe::CanEditChange(const FProperty* InProperty) const{ return bool(); }
EDataValidationResult UFGRecipe::IsDataValid(TArray<FText>& ValidationErrors){ return EDataValidationResult::Valid; }
#endif 
#if WITH_EDITOR
void UFGRecipe::SetProduct(TSubclassOf< UFGRecipe > recipe, TArray< FItemAmount > product){ }
#endif 
UFGRecipe::UFGRecipe() : Super() {
	this->mDisplayNameOverride = false;
	this->mDisplayName = INVTEXT("");
	this->mOverriddenCategory = nullptr;
	this->mManufacturingMenuPriority = 0.0;
	this->mManufactoringDuration = 1.0;
	this->mManualManufacturingMultiplier = 1.0;
	this->mMaterialCustomizationRecipe = nullptr;
	this->mVariablePowerConsumptionConstant = 0.0;
	this->mVariablePowerConsumptionFactor = 1.0;
}
FText UFGRecipe::GetRecipeName(TSubclassOf< UFGRecipe > inClass){ return FText(); }
TArray< FItemAmount > UFGRecipe::GetIngredients(TSubclassOf< UFGRecipe > inClass){ return TArray<FItemAmount>(); }
TArray< FItemAmount > UFGRecipe::GetProducts(TSubclassOf< UFGRecipe > inClass, bool allowChildRecipes){ return TArray<FItemAmount>(); }
TSubclassOf< UFGItemCategory > UFGRecipe::GetCategory(TSubclassOf< UFGRecipe > inClass){ return TSubclassOf<UFGItemCategory>(); }
float UFGRecipe::GetManufacturingMenuPriority(TSubclassOf< UFGRecipe > inClass){ return float(); }
float UFGRecipe::GetManufacturingDuration(TSubclassOf< UFGRecipe > inClass){ return float(); }
float UFGRecipe::GetManualManufacturingDuration(TSubclassOf< UFGRecipe > inClass){ return float(); }
TArray< TSubclassOf< UObject > > UFGRecipe::GetProducedIn(TSubclassOf< UFGRecipe > inClass){ return TArray<TSubclassOf<UObject> >(); }
bool UFGRecipe::HasAnyProducers(TSubclassOf< UFGRecipe > inClass){ return bool(); }
bool UFGRecipe::IsRecipeAffordable( AFGCharacterPlayer* player, TSubclassOf<  UFGRecipe > recipe){ return bool(); }
void UFGRecipe::SortByName(TArray< TSubclassOf< UFGRecipe > >& recipes){ }
void UFGRecipe::SortByManufacturingMenuPriority(TArray< TSubclassOf< UFGRecipe > >& recipes){ }
TSubclassOf< class UFGCustomizationRecipe > UFGRecipe::GetMaterialCustomizationRecipe(TSubclassOf< UFGRecipe > recipe){ return TSubclassOf<class UFGCustomizationRecipe>(); }
TSubclassOf< class UFGItemDescriptor > UFGRecipe::GetDescriptorForRecipe(TSubclassOf<  UFGRecipe > recipe){ return TSubclassOf<class UFGItemDescriptor>(); }
TArray< EEvents > UFGRecipe::GetRelevantEvents(TSubclassOf< UFGRecipe > inClass){ return TArray<EEvents>(); }
FText UFGRecipe::GetDisplayName() const{ return FText(); }
void UFGRecipe::GetProducedIn(TArray< TSubclassOf< UObject > >& out_producedIn) const{ }
bool UFGRecipe::IsProducedIn(TSubclassOf<  UFGRecipe > inClass, TSubclassOf< UObject > inProducer){ return bool(); }
