// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSubsystem.h"

AFGSubsystem::AFGSubsystem(){ 
	this->bAlwaysRelevant = true;
	this->bReplicates = true;
}
