// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGVolumeMapArea.h"
#include "Components/BrushComponent.h"

#if WITH_EDITOR
void AFGVolumeMapArea::CheckForErrors(){ Super::CheckForErrors(); }
#endif 
AFGVolumeMapArea::AFGVolumeMapArea(){ 
	this->mMapArea = nullptr;
	this->RootComponent = CreateDefaultSubobject<UBrushComponent>(TEXT("BrushComponent0"));
}
void AFGVolumeMapArea::BeginPlay(){ }
void AFGVolumeMapArea::OnPrimitiveComponentEntered(UPrimitiveComponent* overlappedComp, AActor* other, UPrimitiveComponent* otherComp, int32 otherBodyIndex, bool fromSweep, const FHitResult& sweepResult){ }
void AFGVolumeMapArea::OnPawnEntered(APawn* pawn, const FHitResult& enterInfo){ }
