// This file has been automatically generated by the Unreal Header Implementation tool

#include "Environment/FGGasPillarDesctructionActor.h"

AFGGasPillarDesctructionActor::AFGGasPillarDesctructionActor(){ }
void AFGGasPillarDesctructionActor::BeginPlay(){ }
void AFGGasPillarDesctructionActor::SetDestructionInfo(float dmgScale, const FVector& dmgLocation){ }
