// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWaterfall.h"

AFGWaterfall::AFGWaterfall(){ }
void AFGWaterfall::BeginPlay(){ }
void AFGWaterfall::Tick(float DeltaTime){ }
