// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/Enemy/FGEnemy.h"
#include "FGHealthComponent.h"
#include "Components/CapsuleComponent.h"
#include "AIController.h"

void AFGEnemy::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
AFGEnemy::AFGEnemy(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { 
	this->mCurrentAttack = nullptr;
	this->mCurrentAggroTarget = nullptr;
	this->mHealthComponent = CreateDefaultSubobject<UFGHealthComponent>(TEXT("HealthComponent"));
	this->AIControllerClass = AAIController::StaticClass();
	this->RootComponent = CreateDefaultSubobject<UCapsuleComponent>(TEXT("CollisionCylinder"));
}
FVector AFGEnemy::GetAttackLocation_Implementation(){ return FVector(); }
void AFGEnemy::PerformCustomRadialAttack_Implementation(){ }
void AFGEnemy::SetCurrentAggroTarget(AActor* newTarget){ }
void AFGEnemy::OnCurrentAggroTargetReplicated_Implementation(){ }
void AFGEnemy::OnRep_CurrentAggroTarget(){ }
