// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGTapeDescriptor.h"

TSoftClassPtr< class UFGTapeData > UFGTapeDescriptor::GetTapeData(TSubclassOf<  UFGItemDescriptor > inClass){ return TSoftClassPtr<class UFGTapeData>(); }
