// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/Enemy/FGCrabHatcher.h"

AFGCrabHatcher::AFGCrabHatcher(){ }
void AFGCrabHatcher::PreSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrabHatcher::PostSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrabHatcher::PreLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrabHatcher::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrabHatcher::GatherDependencies_Implementation(TArray<UObject*>& out_dependentObjects){ }
bool AFGCrabHatcher::NeedTransform_Implementation(){ return bool(); }
bool AFGCrabHatcher::ShouldSave_Implementation() const{ return bool(); }
float AFGCrabHatcher::TakeDamage(float DamageAmount, FDamageEvent const& DamageEvent, AController* EventInstigator, AActor* DamageCauser){ return float(); }
void AFGCrabHatcher::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGCrabHatcher::RegisterHostilePlayer( AFGCharacterPlayer* player){ }
AFGFlyingBabyCrab* AFGCrabHatcher::SpawnBabyCrab(){ return nullptr; }
void AFGCrabHatcher::OnBabyCrabDestroyed( AActor* babyCrabActor){ }
