// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGEnemy.h"

AFGEnemy::AFGEnemy(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
