// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFlyingBabyCrab.h"

AFGFlyingBabyCrab::AFGFlyingBabyCrab(){ }
void AFGFlyingBabyCrab::BeginPlay(){ }
void AFGFlyingBabyCrab::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
void AFGFlyingBabyCrab::PostNetReceiveLocationAndRotation(){ }
