// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureDescriptor.h"

UTexture2D* UFGCreatureDescriptor::Internal_GetSmallIcon() const{ return nullptr; }
UTexture2D* UFGCreatureDescriptor::Internal_GetBigIcon() const{ return nullptr; }
