// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureFamily.h"

UFGCreatureFamily::UFGCreatureFamily(){ }
ECreatureFamilyHostility UFGCreatureFamily::GetHostilityTowards(TSubclassOf< UFGCreatureFamily > otherFamily) const{ return ECreatureFamilyHostility(); }
