// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAISystem.h"

UFGAISystem::UFGAISystem(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
