// This file has been automatically generated by the Unreal Header Implementation tool

#include "AI/FGDamageTypeAccumulator.h"

UFGDamageTypeAccumulator::UFGDamageTypeAccumulator(){ }
bool UFGDamageTypeAccumulator::ShouldAccumulateForDamage(const  AFGCreatureController* controller, float damageAmount, const UFGDamageType* damageType, const AActor* sourceActor) const{ return bool(); }
float UFGDamageTypeAccumulator::GetAccumulation(float damageAmount, const UFGDamageType* damageType, const AActor* sourceActor) const{ return float(); }
