// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGStimulusAccumulator.h"

UFGStimulusAccumulator::UFGStimulusAccumulator(){ }
bool UFGStimulusAccumulator::ShouldAccumulateForStimulus(const  AFGCreatureController* controller, const FAIStimulus& stimulus, const AActor* sourceActor) const{ return bool(); }
float UFGStimulusAccumulator::GetAccumulation(const FAIStimulus& stimulus, const AActor* sourceActor) const{ return float(); }
bool UFGStimulusAccumulatorNoise::ShouldAccumulateForStimulus(const  AFGCreatureController* controller, const FAIStimulus& stimulus, const AActor* sourceActor) const{ return bool(); }
bool UFGStimulusAccumulatorSense::ShouldAccumulateForStimulus(const  AFGCreatureController* controller, const FAIStimulus& stimulus, const AActor* sourceActor) const{ return bool(); }
