// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGReplicationDetailInventoryComponent.h"
#include "FGInventoryComponent.h"

UFGReplicationDetailInventoryComponent::UFGReplicationDetailInventoryComponent(){ }
void UFGReplicationDetailInventoryComponent::SetMainInventoryComponent( UFGInventoryComponent* inventoryComponent){ }
void UFGReplicationDetailInventoryComponent::SetReplicationInventoryComponent( UFGInventoryComponent* inventoryComponent){ }
void UFGReplicationDetailInventoryComponent::ClearReplicationInventoryComponent(){ }
