// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGReplicationDetailInventoryComponent.h"

void FReplicationDetailData::SetMainInventoryComponent(UFGInventoryComponent* inventoryComponent){ }
void FReplicationDetailData::SetReplicationInventoryComponent(UFGInventoryComponent* inventoryComponent){ }
void FReplicationDetailData::ClearReplicationInventoryComponent(){ }
