// This file has been automatically generated by the Unreal Header Implementation tool

#include "Replication/FGReplicationDetailActor_ResourceSink.h"

AFGReplicationDetailActor_ResourceSink::AFGReplicationDetailActor_ResourceSink(){ }
void AFGReplicationDetailActor_ResourceSink::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGReplicationDetailActor_ResourceSink::InitReplicationDetailActor( AFGBuildable* owningActor){ }
void AFGReplicationDetailActor_ResourceSink::FlushReplicationActorStateToOwner(){ }
bool AFGReplicationDetailActor_ResourceSink::HasCompletedInitialReplication() const{ return bool(); }
