// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGStaticReplicatedActor.h"

AFGStaticReplicatedActor::AFGStaticReplicatedActor() : Super() {
	this->SetReplicates(true);
	this->NetDormancy = DORM_Initial;
}
