// This file has been automatically generated by the Unreal Header Implementation tool

#include "Resources/FGDecorDescriptor.h"
#include "Buildables/FGBuildableDecor.h"

UFGDecorDescriptor::UFGDecorDescriptor(){ 
	this->mDecorMesh = nullptr;
	this->mBuildableClass = AFGBuildableDecor::StaticClass();
}
UStaticMesh* UFGDecorDescriptor::GetDecorMesh(TSubclassOf< UFGDecorDescriptor > inClass){ return nullptr; }
