// This file has been automatically generated by the Unreal Header Implementation tool

#include "Resources/FGNoneDescriptor.h"

UFGNoneDescriptor::UFGNoneDescriptor(){ 
	this->mDisplayName = NSLOCTEXT("NoneDescriptor", "DisplayName", "None");
	this->mDescription = NSLOCTEXT("NoneDescriptor", "Description", "Nothing");
}
