// This file has been automatically generated by the Unreal Header Implementation tool

#include "Resources/FGOverflowDescriptor.h"

UFGOverflowDescriptor::UFGOverflowDescriptor(){ 
	this->mDisplayName = NSLOCTEXT("OverflowDescriptor", "DisplayName", "Overflow");
	this->mDescription = NSLOCTEXT("OverflowDescriptor", "Description", "Overflow Output");
}
