// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGActionScorerCompound.h"

void UFGActionScorerCompound::Initialize_Native(UFGAction* action){ }
bool UFGActionScorerCompound::GetScore_Implementation(float& out_score) const{ return bool(); }
