// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureActionAnimated.h"

UFGCreatureActionAnimated::UFGCreatureActionAnimated(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGCreatureActionAnimated::PerformAction_Implementation(){ }
void UFGCreatureActionAnimated::OnAnimationFinished_Implementation( UAnimMontage* montage, bool WasInterrupted){ }
