// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/Actions/FGCreatureActionProjectileCharge.h"

UFGCreatureActionProjectileCharge::UFGCreatureActionProjectileCharge(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGCreatureActionProjectileCharge::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
bool UFGCreatureActionProjectileCharge::InitializeAction(AController* controller, APawn* pawn){ return bool(); }
void UFGCreatureActionProjectileCharge::InternalActionCleanup(bool actionSuccess){ }
void UFGCreatureActionProjectileCharge::BeginCharge_Implementation(){ }
void UFGCreatureActionProjectileCharge::EndCharge_Implementation(){ }
void UFGCreatureActionProjectileCharge::FireProjectile(){ }
void UFGCreatureActionProjectileCharge::FireActiveChargeProjectile_Implementation(){ }
void UFGCreatureActionProjectileCharge::StartActiveChargeProjectiles(){ }
void UFGCreatureActionProjectileCharge::StopActiveChargeProjectiles(){ }
