// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/Actions/FGCreatureActionMeleeAttack.h"

UFGCreatureActionMeleeAttack::UFGCreatureActionMeleeAttack(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
bool UFGCreatureActionMeleeAttack::CanPerformAction_Implementation() const{ return bool(); }
void UFGCreatureActionMeleeAttack::PerformAction_Implementation(){ }
void UFGCreatureActionMeleeAttack::ActionTick_Implementation(float DeltaTime){ }
void UFGCreatureActionMeleeAttack::CleanupAction_Implementation(bool ActionSuccess){ }
void UFGCreatureActionMeleeAttack::OnAnimNotify_Implementation(const UFGAnimNotify* Notify){ }
void UFGCreatureActionMeleeAttack::ProcessHit_Implementation( AFGCharacterBase* HitCharacter, const FHitResult& HitResult){ }
void UFGCreatureActionMeleeAttack::StartMeleeAttack_Implementation(){ }
void UFGCreatureActionMeleeAttack::OnTargetReached(FAIRequestID RequestID, EPathFollowingResult::Type Result){ }
EPathFollowingRequestResult::Type UFGCreatureActionMeleeAttack::MoveToTarget(){ return EPathFollowingRequestResult::Type(); }
void UFGCreatureActionMeleeAttack::NetMulticast_ProcessHits_Implementation(const TArray< FFGMeleeAttackHit >& hits){ }
void UFGCreatureActionMeleeAttack::ProcessHits(const TArray< FFGMeleeAttackHit >& hits){ }
