// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/Actions/FGCreatureActionLeapAttack.h"

UFGCreatureActionLeapAttack::UFGCreatureActionLeapAttack(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGCreatureActionLeapAttack::PerformAction_Implementation(){ }
bool UFGCreatureActionLeapAttack::CanPerformAction_Implementation() const{ return bool(); }
void UFGCreatureActionLeapAttack::CleanupAction_Implementation(bool actionSuccess){ }
void UFGCreatureActionLeapAttack::ActionTick_Implementation(float DeltaTime){ }
void UFGCreatureActionLeapAttack::StartLeapAttack(){ }
void UFGCreatureActionLeapAttack::OnAnimationFinished_Implementation( UAnimMontage* montage, bool WasInterrupted){ }
void UFGCreatureActionLeapAttack::OnAnimationBlendingOut_Implementation( UAnimMontage* montage, bool WasInterrupted){ }
void UFGCreatureActionLeapAttack::OnCreatureLandedCallback(const FHitResult& hitResult){ }
void UFGCreatureActionLeapAttack::OnCreatureLanded_Implementation(const FHitResult& hitResult){ }
void UFGCreatureActionLeapAttack::OnLeapStarted_Implementation(){ }
bool UFGCreatureActionLeapAttack::LaunchToTarget(AActor* target){ return bool(); }
bool UFGCreatureActionLeapAttack::LaunchToLocation(const FVector& destination){ return bool(); }
void UFGCreatureActionLeapAttack::ProcessHit_Implementation( AFGCharacterBase* character, const FHitResult& hitResult){ }
void UFGCreatureActionLeapAttack::ProcessSlamHit_Implementation( AFGCharacterBase* character, const FHitResult& hitResult){ }
void UFGCreatureActionLeapAttack::ClearAllHitCharacters(){ }
void UFGCreatureActionLeapAttack::ClearHitCharacter( AFGCharacterBase* character){ }
void UFGCreatureActionLeapAttack::OnHitCharacterCleared_Implementation( AFGCharacterBase* character){ }
void UFGCreatureActionLeapAttack::ProcessHit_Internal( AFGCharacterBase* character, const FHitResult& hitResult){ }
void UFGCreatureActionLeapAttack::NetMulticast_OnLeapStarted_Implementation(){ }
void UFGCreatureActionLeapAttack::NetMulticast_OnCreatureLanded_Implementation(const FHitResult& hitResult){ }
