// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureActionForwardJump.h"

UFGCreatureActionForwardJump::UFGCreatureActionForwardJump(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGCreatureActionForwardJump::PerformAction_Implementation(){ }
void UFGCreatureActionForwardJump::CleanupAction_Implementation(bool actionSuccess){ }
void UFGCreatureActionForwardJump::Jump_Implementation(){ }
void UFGCreatureActionForwardJump::OnLanded_Implementation(){ }
FVector UFGCreatureActionForwardJump::GetLaunchVelocity_Implementation(){ return FVector(); }
void UFGCreatureActionForwardJump::OnAnimationFinished_Implementation(UAnimMontage* montage, bool WasInterrupted){ }
void UFGCreatureActionForwardJump::OnCreatureLandedCallback(const FHitResult& hitResult){ }
