// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureActionPull.h"

UFGCreatureActionPull::UFGCreatureActionPull(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGCreatureActionPull::PerformAction_Implementation(){ }
void UFGCreatureActionPull::OnAnimNotify_Implementation(const UFGAnimNotify* Notify){ }
bool UFGCreatureActionPull::PerformPull(){ return bool(); }
