// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreatureActionRoar.h"

UFGCreatureActionRoar::UFGCreatureActionRoar(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGCreatureActionRoar::PerformAction_Implementation(){ }
void UFGCreatureActionRoar::InternalActionCleanup(bool actionSuccess){ }
void UFGCreatureActionRoar::OnAnimNotify_Implementation(const UFGAnimNotify* Notify){ }
void UFGCreatureActionRoar::OnAnimationFinished_Implementation( UAnimMontage* montage, bool WasInterrupted){ }
void UFGCreatureActionRoar::OnBeginRoar_Implementation(){ }
void UFGCreatureActionRoar::OnEndRoar_Implementation(){ }
void UFGCreatureActionRoar::BeginRoar_Implementation(){ }
void UFGCreatureActionRoar::EndRoar_Implementation(){ }
void UFGCreatureActionRoar::MakeRoarNoise(){ }
void UFGCreatureActionRoar::StopNoiseTimer(){ }
