// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/Actions/FGCreatureActionAmmoAttack.h"

UFGCreatureActionAmmoAttack::UFGCreatureActionAmmoAttack(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGCreatureActionAmmoAttack::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
bool UFGCreatureActionAmmoAttack::InitializeAction(AController* controller, APawn* pawn){ return bool(); }
void UFGCreatureActionAmmoAttack::PerformAction_Implementation(){ }
void UFGCreatureActionAmmoAttack::OnAnimNotify_Implementation(const UFGAnimNotify* Notify){ }
void UFGCreatureActionAmmoAttack::InternalActionCleanup(bool actionSuccess){ }
void UFGCreatureActionAmmoAttack::FireProjectile(){ }
void UFGCreatureActionAmmoAttack::OnProjectileFired(AActor* spawnedProjectile){ }
