// This file has been automatically generated by the Unreal Header Implementation tool

#include "SharedInventoryStatePtr.h"

return FSharedInventoryStatePtr::FSharedInventoryStatePtr( actor ){ return return(); }
FSharedInventoryStatePtr::FSharedInventoryStatePtr( state.ActorPtr ){ }
