// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGUserSetting.h"

#if WITH_EDITOR
bool UFGUserSetting::SetupValueFunction( UK2Node_CallFunction* callFunction, bool isGetterFunction) const{ return bool(); }
EDataValidationResult UFGUserSetting::IsDataValid(TArray<FText>& ValidationErrors){ return EDataValidationResult::Valid; }
#endif 
UFGUserSetting::UFGUserSetting(){ }
FOptionRowData UFGUserSetting::ToOptionRowData() const{ return FOptionRowData(); }
bool UFGUserSetting::ShouldShowInCurrentConfig(UWorld* world) const{ return bool(); }
FVariant UFGUserSetting::GetDefaultValue() const{ return FVariant(); }
IFGOptionInterface* UFGUserSetting::GetOptionInterface(){ return nullptr; }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting::GetValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
bool UFGUserSetting::HasVisibilityDisqualifier(ESettingVisiblityDisqualifier disqualifier) const{ return bool(); }
bool UFGUserSetting::HasEditabilityDisqualifier(ESettingEditabilityDisqualifier disqualifier) const{ return bool(); }
bool UFGUserSetting::ShouldShowInBuild() const{ return bool(); }
#if WITH_EDITOR
FName UFGUserSetting_ValueSelector::GetGraphSchemaName() const{ return FName(); }
#endif 
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_ValueSelector::GetValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
#if WITH_EDITOR
FName UFGUserSetting_CheckBox::GetGraphSchemaName() const{ return FName(); }
bool UFGUserSetting_CheckBox::SetupValueFunction( UK2Node_CallFunction* callFunction, bool isGetterFunction) const{ return bool(); }
#endif 
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_CheckBox::GetValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_EnumSelector::GetValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
TArray<FIntegerSelection> UFGUserSetting_EnumSelector::GetIntegerSelectionValues(int32& out_DefaultSelectionIndex){ return TArray<FIntegerSelection>(); }
TArray<FString> UFGUserSetting_EnumSelector::GetEnumOptions() const{ return TArray<FString>(); }
#if WITH_EDITOR
FName UFGUserSetting_IntSelector::GetGraphSchemaName() const{ return FName(); }
bool UFGUserSetting_IntSelector::SetupValueFunction( UK2Node_CallFunction* callFunction, bool isGetterFunction) const{ return bool(); }
#endif 
UFGUserSetting_IntSelector::UFGUserSetting_IntSelector(){ }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_IntSelector::GetValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
#if WITH_EDITOR
bool UFGUserSetting_Slider::SetupValueFunction( UK2Node_CallFunction* callFunction, bool isGetterFunction) const{ return bool(); }
#endif 
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_Slider::GetValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
FVariant UFGUserSetting_Slider::GetDefaultValue() const{ return FVariant(); }
