// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGUserSetting.h"

FOptionRowData UFGUserSetting::ToOptionRowData() const{ return FOptionRowData(); }
bool UFGUserSetting::ShouldShowInBuild() const{ return bool(); }
void UFGUserSetting::RestoreToDefaultValue(){ }
FVariant UFGUserSetting::GetDefaultValue() const{ return FVariant(); }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_ValueSelector::GetSettingValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_CheckBox::GetSettingValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_EnumSelector::GetSettingValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
TArray<FIntegerSelection> UFGUserSetting_EnumSelector::GetIntegerSelectionValues(int32& out_DefaultSelectionIndex){ return TArray<FIntegerSelection>(); }
TArray<FString> UFGUserSetting_EnumSelector::GetEnumOptions() const{ return TArray<FString>(); }
UFGUserSetting_IntSelector::UFGUserSetting_IntSelector(){ }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_IntSelector::GetSettingValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_Slider::GetSettingValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
TSubclassOf< class UFGOptionsValueController > UFGUserSetting_Custom::GetSettingValueSelectorWidgetClass() const{ return TSubclassOf<class UFGOptionsValueController>(); }
