// This file has been automatically generated by the Unreal Header Implementation tool

#include "Replication/FGReplicationDetailActor_BuildableFactory.h"
#include "Components/SceneComponent.h"

AFGReplicationDetailActor_BuildableFactory::AFGReplicationDetailActor_BuildableFactory(){ 
	this->mInventoryPotential = nullptr;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("ReplicationDetailActor"));
}
void AFGReplicationDetailActor_BuildableFactory::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGReplicationDetailActor_BuildableFactory::InitReplicationDetailActor( AFGBuildable* owningActor){ }
void AFGReplicationDetailActor_BuildableFactory::FlushReplicationActorStateToOwner(){ }
bool AFGReplicationDetailActor_BuildableFactory::HasCompletedInitialReplication() const{ return bool(); }
void AFGReplicationDetailActor_BuildableFactory::OnRep_Inventory(){ }
