// This file has been automatically generated by the Unreal Header Implementation tool

#include "Replication/FGRepDetailActor_Extractor.h"
#include "Components/SceneComponent.h"

AFGRepDetailActor_Extractor::AFGRepDetailActor_Extractor(){ 
	this->mOutputInventory = nullptr;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("ReplicationDetailActor"));
}
void AFGRepDetailActor_Extractor::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGRepDetailActor_Extractor::InitReplicationDetailActor( AFGBuildable* owningActor){ }
void AFGRepDetailActor_Extractor::RemoveDetailActorFromOwner(){ }
void AFGRepDetailActor_Extractor::FlushReplicationActorStateToOwner(){ }
bool AFGRepDetailActor_Extractor::HasCompletedInitialReplication() const{ return bool(); }
