// This file has been automatically generated by the Unreal Header Implementation tool

#include "WheeledVehicles/FGSimulatedWheeledVehicle.h"

AFGSimulatedWheeledVehicle::AFGSimulatedWheeledVehicle(){ }
void AFGSimulatedWheeledVehicle::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGSimulatedWheeledVehicle::Init( AFGWheeledVehicle* vehicle){ }
void AFGSimulatedWheeledVehicle::BeginPlay(){ }
void AFGSimulatedWheeledVehicle::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
