// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWheeledVehicleDetectionComponent.h"

UFGWheeledVehicleDetectionComponent::UFGWheeledVehicleDetectionComponent(){ }
void UFGWheeledVehicleDetectionComponent::Init( AFGWheeledVehicle* vehicle, UWheeledVehicleMovementComponent* movement){ }
void UFGWheeledVehicleDetectionComponent::OnCreatePhysicsState(){ }
void UFGWheeledVehicleDetectionComponent::BeginPlay(){ }
void UFGWheeledVehicleDetectionComponent::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
void UFGWheeledVehicleDetectionComponent::TickComponent(float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction){ }
void UFGWheeledVehicleDetectionComponent::OnOverlapBegin(UPrimitiveComponent* OverlappedComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult){ }
void UFGWheeledVehicleDetectionComponent::OnOverlapEnd(UPrimitiveComponent* OverlappedComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex){ }
