// This file has been automatically generated by the Unreal Header Implementation tool

#include "UI/Message/FGAudioMessage.h"

bool FMessageDialogue::HasMoreSubtitlesToShow() const{ return bool(); }
FMessageSubtitle FMessageDialogue::PopNextSubtitle(float subtitleTimeMultiplier){ return FMessageSubtitle(); }
UFGAudioMessage::UFGAudioMessage(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
void UFGAudioMessage::NativeConstruct(){ }
void UFGAudioMessage::NativeDestruct(){ }
void UFGAudioMessage::StartPlayback(){ }
void UFGAudioMessage::OnSkipButtonPressed(){ }
void UFGAudioMessage::OnSkipButtonReleased(){ }
void UFGAudioMessage::PlayNextDialogue_Implementation(){ }
void UFGAudioMessage::ContinuePlayback(){ }
void UFGAudioMessage::CancelPlayback(){ }
void UFGAudioMessage::FinishPlayback(){ }
FAudioSubtitlePair UFGAudioMessage::GetCurrentDialogue(){ return FAudioSubtitlePair(); }
EMessagePriorityType UFGAudioMessage::GetMessagePriorityType(TSubclassOf< UFGAudioMessage > message, UObject* worldContext){ return EMessagePriorityType(); }
void UFGAudioMessage::InitMessage( UFGMessage* message){ }
